;  Assembly code generated by mikroVirtualMachine - V. 5.0.0.3
;  Date/Time: 24/05/2016 20:34:23
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2804			GOTO	_main
$0982	$	_usart_write:
;USART_c67.ppas,40 :: 		
;USART_c67.ppas,42 :: 		
$0982	$	USART_c67_L_14:
$0982	$1303			BCF	STATUS, RP1
$0983	$1683			BSF	STATUS, RP0
$0984	$0818			MOVF	TXSTA, 0
$0985	$00F1			MOVWF	STACK_1
$0986	$3000			MOVLW	0
$0987	$18F1			BTFSC	STACK_1, 1
$0988	$3001			MOVLW	1
$0989	$00F1			MOVWF	STACK_1
$098A	$0871			MOVF	STACK_1, 0
$098B	$3A00			XORLW	0
$098C	$1D03			BTFSS	STATUS, Z
$098D	$2990			GOTO	USART_c67_L_15
;USART_c67.ppas,43 :: 		
$098E	$0000			NOP
$098F	$2982			GOTO	USART_c67_L_14
$0990	$	USART_c67_L_15:
;USART_c67.ppas,44 :: 		
$0990	$1283			BCF	STATUS, RP0
$0991	$085D			MOVF	FARG_USART_Write, 0
$0992	$0099			MOVWF	TXREG
$0993	$	USART_c67_L_12:
;USART_c67.ppas,45 :: 		
$0993	$0008			RETURN
$09A2	$	_usart_data_ready:
;USART_c67.ppas,48 :: 		
;USART_c67.ppas,50 :: 		
$09A2	$1303			BCF	STATUS, RP1
$09A3	$1283			BCF	STATUS, RP0
$09A4	$080C			MOVF	PIR1, 0
$09A5	$00F1			MOVWF	STACK_1
$09A6	$3000			MOVLW	0
$09A7	$1AF1			BTFSC	STACK_1, 5
$09A8	$3001			MOVLW	1
$09A9	$00F1			MOVWF	STACK_1
$09AA	$0871			MOVF	STACK_1, 0
$09AB	$00DD			MOVWF	_usart_data_ready_local_result
$09AC	$	USART_c67_L_18:
;USART_c67.ppas,51 :: 		
$09AC	$085D			MOVF	_usart_data_ready_local_result, 0
$09AD	$00F0			MOVWF	STACK_0
$09AE	$0008			RETURN
$096F	$	_usart_read:
;USART_c67.ppas,54 :: 		
;USART_c67.ppas,55 :: 		
$096F	$1303			BCF	STATUS, RP1
$0970	$1283			BCF	STATUS, RP0
$0971	$081A			MOVF	RCREG, 0
$0972	$00DD			MOVWF	_usart_read_local_result
;USART_c67.ppas,61 :: 		
$0973	$0818			MOVF	RCSTA, 0
$0974	$00F1			MOVWF	STACK_1
$0975	$3000			MOVLW	0
$0976	$18F1			BTFSC	STACK_1, 1
$0977	$3001			MOVLW	1
$0978	$00F1			MOVWF	STACK_1
$0979	$0871			MOVF	STACK_1, 0
$097A	$3A01			XORLW	1
$097B	$1D03			BTFSS	STATUS, Z
$097C	$297F			GOTO	USART_c67_L_21
$097D	$	USART_c67_L_20:
;USART_c67.ppas,63 :: 		
$097D	$1218			BCF	RCSTA, 4
$097E	$	USART_c67_L_24:
;USART_c67.ppas,64 :: 		
$097E	$	USART_c67_L_25:
$097E	$1618			BSF	RCSTA, 4
$097F	$	USART_c67_L_26:
;USART_c67.ppas,65 :: 		
$097F	$	USART_c67_L_21:
$097F	$	USART_c67_L_22:
$097F	$	USART_c67_L_19:
;USART_c67.ppas,66 :: 		
$097F	$085D			MOVF	_usart_read_local_result, 0
$0980	$00F0			MOVWF	STACK_0
$0981	$0008			RETURN
$09AF	$	_delay_22us:
;delays.ppas,21 :: 		begin
;delays.ppas,22 :: 		Delay_us(22);
$09AF	$3024			MOVLW	36
$09B0	$1303			BCF	STATUS, RP1
$09B1	$1283			BCF	STATUS, RP0
$09B2	$00FA			MOVWF	STACK_10
$09B3	$0BFA			DECFSZ	STACK_10, F
$09B4	$29B3			GOTO	$-1
$09B5	$0000			NOP
$09B6	$	delays_L_3:
;delays.ppas,23 :: 		end;
$09B6	$0008			RETURN
$093C	$	_div_16x16_u:
$093C	$1303			BCF	STATUS, RP1
$093D	$1283			BCF	STATUS, RP0
;math.ppas,108 :: 		
;math.ppas,110 :: 		
$093E	$01F8			CLRF	STACK_8
;math.ppas,111 :: 		
$093F	$01F9			CLRF	STACK_9
;math.ppas,112 :: 		
$0940	$3010			MOVLW	16
;math.ppas,113 :: 		
$0941	$00FC			MOVWF	STACK_12
;math.ppas,114 :: 		
$0942	$0D71			RLF	STACK_1, W
;math.ppas,115 :: 		
$0943	$0DF8			RLF	STACK_8, F
;math.ppas,116 :: 		
$0944	$0DF9			RLF	STACK_9, F
;math.ppas,117 :: 		
$0945	$0874			MOVF	STACK_4, W
;math.ppas,118 :: 		
$0946	$02F8			SUBWF	STACK_8, F
;math.ppas,119 :: 		
$0947	$0875			MOVF	STACK_5, W
;math.ppas,120 :: 		
$0948	$1C03			BTFSS	STATUS, C
;math.ppas,121 :: 		
$0949	$0F75			INCFSZ	STACK_5, W
;math.ppas,122 :: 		
$094A	$02F9			SUBWF	STACK_9, F
;math.ppas,123 :: 		
$094B	$1803			BTFSC	STATUS, C
;math.ppas,124 :: 		
$094C	$2954			GOTO	$+8
;math.ppas,125 :: 		
$094D	$0874			MOVF	STACK_4, W
;math.ppas,126 :: 		
$094E	$07F8			ADDWF	STACK_8, F
;math.ppas,127 :: 		
$094F	$0875			MOVF	STACK_5, W
;math.ppas,128 :: 		
$0950	$1803			BTFSC	STATUS, C
;math.ppas,129 :: 		
$0951	$0F75			INCFSZ	STACK_5, W
;math.ppas,130 :: 		
$0952	$07F9			ADDWF	STACK_9, F
;math.ppas,131 :: 		
$0953	$1003			BCF	STATUS, C
;math.ppas,132 :: 		
$0954	$0DF0			RLF	STACK_0, F
;math.ppas,133 :: 		
$0955	$0DF1			RLF	STACK_1, F
;math.ppas,134 :: 		
$0956	$0BFC			DECFSZ	STACK_12, F
;math.ppas,135 :: 		
$0957	$2942			GOTO	$-21
;math.ppas,136 :: 		
$0958	$	math_L_3:
;math.ppas,137 :: 		
$0958	$0008			RETURN
$0905	$	_mul_32x32_u:
$0905	$1303			BCF	STATUS, RP1
$0906	$1283			BCF	STATUS, RP0
;math.ppas,1570 :: 		
;math.ppas,1578 :: 		
$0907	$3022			MOVLW	34
;math.ppas,1579 :: 		
$0908	$00FC			MOVWF	STACK_12
;math.ppas,1580 :: 		
$0909	$01F8			CLRF	STACK_8
;math.ppas,1581 :: 		
$090A	$01F9			CLRF	STACK_9
;math.ppas,1582 :: 		
$090B	$01FA			CLRF	STACK_10
;math.ppas,1584 :: 		
$090C	$01FB			CLRF	STACK_11
;math.ppas,1588 :: 		
$090D	$	_NEXT:
;math.ppas,1589 :: 		
$090D	$03FC			DECF	STACK_12, F
;math.ppas,1590 :: 		
$090E	$1903			BTFSC	STATUS, Z
;math.ppas,1591 :: 		
$090F	$293B			GOTO	_EXIT2
;math.ppas,1593 :: 		
$0910	$1003			BCF	STATUS, C
;math.ppas,1602 :: 		
$0911	$	_LOOP:
;math.ppas,1603 :: 		
$0911	$0CFB			RRF	STACK_11, F
;math.ppas,1604 :: 		
$0912	$0CFA			RRF	STACK_10, F
;math.ppas,1605 :: 		
$0913	$0CF9			RRF	STACK_9, F
;math.ppas,1606 :: 		
$0914	$0CF8			RRF	STACK_8, F
;math.ppas,1607 :: 		
$0915	$0CF3			RRF	STACK_3, F
;math.ppas,1608 :: 		
$0916	$0CF2			RRF	STACK_2, F
;math.ppas,1609 :: 		
$0917	$0CF1			RRF	STACK_1, F
;math.ppas,1614 :: 		
$0918	$0CF0			RRF	STACK_0, F
;math.ppas,1615 :: 		
$0919	$1C03			BTFSS	STATUS, C
;math.ppas,1616 :: 		
$091A	$290D			GOTO	_NEXT
;math.ppas,1617 :: 		
$091B	$03FC			DECF	STACK_12, F
;math.ppas,1618 :: 		
$091C	$1903			BTFSC	STATUS, Z
;math.ppas,1625 :: 		
$091D	$292D			GOTO	_EXIT1
;math.ppas,1626 :: 		
$091E	$0874			MOVF	STACK_4, W
;math.ppas,1627 :: 		
$091F	$07F8			ADDWF	STACK_8, F
;math.ppas,1628 :: 		
$0920	$0875			MOVF	STACK_5, W
;math.ppas,1629 :: 		
$0921	$1803			BTFSC	STATUS, C
;math.ppas,1630 :: 		
$0922	$0F75			INCFSZ	STACK_5, W
;math.ppas,1631 :: 		
$0923	$07F9			ADDWF	STACK_9, F
;math.ppas,1632 :: 		
$0924	$0876			MOVF	STACK_6, W
;math.ppas,1633 :: 		
$0925	$1803			BTFSC	STATUS, C
;math.ppas,1634 :: 		
$0926	$0F76			INCFSZ	STACK_6, W
;math.ppas,1635 :: 		
$0927	$07FA			ADDWF	STACK_10, F
;math.ppas,1636 :: 		
$0928	$0877			MOVF	STACK_7, W
;math.ppas,1637 :: 		
$0929	$1803			BTFSC	STATUS, C
;math.ppas,1638 :: 		
$092A	$0F77			INCFSZ	STACK_7, W
;math.ppas,1640 :: 		
$092B	$07FB			ADDWF	STACK_11, F
;math.ppas,1642 :: 		
$092C	$2911			GOTO	_LOOP
;math.ppas,1647 :: 		
$092D	$	_EXIT1:
;math.ppas,1648 :: 		
$092D	$0874			MOVF	STACK_4, W
;math.ppas,1649 :: 		
$092E	$07F8			ADDWF	STACK_8, F
;math.ppas,1650 :: 		
$092F	$0875			MOVF	STACK_5, W
;math.ppas,1651 :: 		
$0930	$1803			BTFSC	STATUS, C
;math.ppas,1652 :: 		
$0931	$0F75			INCFSZ	STACK_5, W
;math.ppas,1653 :: 		
$0932	$07F9			ADDWF	STACK_9, F
;math.ppas,1654 :: 		
$0933	$0876			MOVF	STACK_6, W
;math.ppas,1655 :: 		
$0934	$1803			BTFSC	STATUS, C
;math.ppas,1656 :: 		
$0935	$0F76			INCFSZ	STACK_6, W
;math.ppas,1657 :: 		
$0936	$07FA			ADDWF	STACK_10, F
;math.ppas,1658 :: 		
$0937	$0877			MOVF	STACK_7, W
;math.ppas,1659 :: 		
$0938	$1803			BTFSC	STATUS, C
;math.ppas,1660 :: 		
$0939	$0F77			INCFSZ	STACK_7, W
;math.ppas,1663 :: 		
$093A	$07FB			ADDWF	STACK_11, F
;math.ppas,1664 :: 		
$093B	$	_EXIT2:
;math.ppas,1665 :: 		
$093B	$	math_L_13:
;math.ppas,1666 :: 		
$093B	$0008			RETURN
$051C	$	_sdiv3232l:
$051C	$1303			BCF	STATUS, RP1
$051D	$1283			BCF	STATUS, RP0
;math.ppas,539 :: 		
;math.ppas,541 :: 		
$051E	$0874			MOVF	STACK_4, W
;math.ppas,542 :: 		
$051F	$02F8			SUBWF	STACK_8, F
;math.ppas,543 :: 		
$0520	$0875			MOVF	STACK_5, W
;math.ppas,544 :: 		
$0521	$1C03			BTFSS	STATUS, C
;math.ppas,545 :: 		
$0522	$0F75			INCFSZ	STACK_5, W
;math.ppas,546 :: 		
$0523	$02F9			SUBWF	STACK_9, F
;math.ppas,547 :: 		
$0524	$0876			MOVF	STACK_6, W
;math.ppas,548 :: 		
$0525	$1C03			BTFSS	STATUS, C
;math.ppas,549 :: 		
$0526	$0F76			INCFSZ	STACK_6, W
;math.ppas,550 :: 		
$0527	$02FA			SUBWF	STACK_10, F
;math.ppas,551 :: 		
$0528	$0877			MOVF	STACK_7, W
;math.ppas,552 :: 		
$0529	$1C03			BTFSS	STATUS, C
;math.ppas,553 :: 		
$052A	$0F77			INCFSZ	STACK_7, W
;math.ppas,554 :: 		
$052B	$02FB			SUBWF	STACK_11, F
;math.ppas,556 :: 		
$052C	$0DF3			RLF	STACK_3, F
;math.ppas,557 :: 		
$052D	$3007			MOVLW	7
;math.ppas,559 :: 		
$052E	$00FC			MOVWF	STACK_12
;math.ppas,560 :: 		
$052F	$	LOOPS3232A:
;math.ppas,561 :: 		
$052F	$0D73			RLF	STACK_3, W
;math.ppas,562 :: 		
$0530	$0DF8			RLF	STACK_8, F
;math.ppas,563 :: 		
$0531	$0DF9			RLF	STACK_9, F
;math.ppas,564 :: 		
$0532	$0DFA			RLF	STACK_10, F
;math.ppas,565 :: 		
$0533	$0DFB			RLF	STACK_11, F
;math.ppas,566 :: 		
$0534	$0874			MOVF	STACK_4, W
;math.ppas,567 :: 		
$0535	$1C73			BTFSS	STACK_3, 0
;math.ppas,569 :: 		
$0536	$2D45			GOTO	SADD22LA
;math.ppas,570 :: 		
$0537	$02F8			SUBWF	STACK_8, F
;math.ppas,571 :: 		
$0538	$0875			MOVF	STACK_5, W
;math.ppas,572 :: 		
$0539	$1C03			BTFSS	STATUS, C
;math.ppas,573 :: 		
$053A	$0F75			INCFSZ	STACK_5, W
;math.ppas,574 :: 		
$053B	$02F9			SUBWF	STACK_9, F
;math.ppas,575 :: 		
$053C	$0876			MOVF	STACK_6, W
;math.ppas,576 :: 		
$053D	$1C03			BTFSS	STATUS, C
;math.ppas,577 :: 		
$053E	$0F76			INCFSZ	STACK_6, W
;math.ppas,578 :: 		
$053F	$02FA			SUBWF	STACK_10, F
;math.ppas,579 :: 		
$0540	$0877			MOVF	STACK_7, W
;math.ppas,580 :: 		
$0541	$1C03			BTFSS	STATUS, C
;math.ppas,581 :: 		
$0542	$0F77			INCFSZ	STACK_7, W
;math.ppas,582 :: 		
$0543	$02FB			SUBWF	STACK_11, F
;math.ppas,584 :: 		
$0544	$2D52			GOTO	SOK22LA
;math.ppas,585 :: 		
$0545	$	SADD22LA:
;math.ppas,586 :: 		
$0545	$07F8			ADDWF	STACK_8, F
;math.ppas,587 :: 		
$0546	$0875			MOVF	STACK_5, W
;math.ppas,588 :: 		
$0547	$1803			BTFSC	STATUS, C
;math.ppas,589 :: 		
$0548	$0F75			INCFSZ	STACK_5, W
;math.ppas,590 :: 		
$0549	$07F9			ADDWF	STACK_9, F
;math.ppas,591 :: 		
$054A	$0876			MOVF	STACK_6, W
;math.ppas,592 :: 		
$054B	$1803			BTFSC	STATUS, C
;math.ppas,593 :: 		
$054C	$0F76			INCFSZ	STACK_6, W
;math.ppas,594 :: 		
$054D	$07FA			ADDWF	STACK_10, F
;math.ppas,595 :: 		
$054E	$0877			MOVF	STACK_7, W
;math.ppas,596 :: 		
$054F	$1803			BTFSC	STATUS, C
;math.ppas,597 :: 		
$0550	$0F77			INCFSZ	STACK_7, W
;math.ppas,599 :: 		
$0551	$07FB			ADDWF	STACK_11, F
;math.ppas,600 :: 		
$0552	$	SOK22LA:
;math.ppas,602 :: 		
$0552	$0DF3			RLF	STACK_3, F
;math.ppas,603 :: 		
$0553	$0BFC			DECFSZ	STACK_12, F
;math.ppas,605 :: 		
$0554	$2D2F			GOTO	LOOPS3232A
;math.ppas,606 :: 		
$0555	$0D72			RLF	STACK_2, W
;math.ppas,607 :: 		
$0556	$0DF8			RLF	STACK_8, F
;math.ppas,608 :: 		
$0557	$0DF9			RLF	STACK_9, F
;math.ppas,609 :: 		
$0558	$0DFA			RLF	STACK_10, F
;math.ppas,610 :: 		
$0559	$0DFB			RLF	STACK_11, F
;math.ppas,611 :: 		
$055A	$0874			MOVF	STACK_4, W
;math.ppas,612 :: 		
$055B	$1C73			BTFSS	STACK_3, 0
;math.ppas,614 :: 		
$055C	$2D6B			GOTO	SADD22L8
;math.ppas,615 :: 		
$055D	$02F8			SUBWF	STACK_8, F
;math.ppas,616 :: 		
$055E	$0875			MOVF	STACK_5, W
;math.ppas,617 :: 		
$055F	$1C03			BTFSS	STATUS, C
;math.ppas,618 :: 		
$0560	$0F75			INCFSZ	STACK_5, W
;math.ppas,619 :: 		
$0561	$02F9			SUBWF	STACK_9, F
;math.ppas,620 :: 		
$0562	$0876			MOVF	STACK_6, W
;math.ppas,621 :: 		
$0563	$1C03			BTFSS	STATUS, C
;math.ppas,622 :: 		
$0564	$0F76			INCFSZ	STACK_6, W
;math.ppas,623 :: 		
$0565	$02FA			SUBWF	STACK_10, F
;math.ppas,624 :: 		
$0566	$0877			MOVF	STACK_7, W
;math.ppas,625 :: 		
$0567	$1C03			BTFSS	STATUS, C
;math.ppas,626 :: 		
$0568	$0F77			INCFSZ	STACK_7, W
;math.ppas,627 :: 		
$0569	$02FB			SUBWF	STACK_11, F
;math.ppas,629 :: 		
$056A	$2D78			GOTO	SOK22L8
;math.ppas,630 :: 		
$056B	$	SADD22L8:
;math.ppas,631 :: 		
$056B	$07F8			ADDWF	STACK_8, F
;math.ppas,632 :: 		
$056C	$0875			MOVF	STACK_5, W
;math.ppas,633 :: 		
$056D	$1803			BTFSC	STATUS, C
;math.ppas,634 :: 		
$056E	$0F75			INCFSZ	STACK_5, W
;math.ppas,635 :: 		
$056F	$07F9			ADDWF	STACK_9, F
;math.ppas,636 :: 		
$0570	$0876			MOVF	STACK_6, W
;math.ppas,637 :: 		
$0571	$1803			BTFSC	STATUS, C
;math.ppas,638 :: 		
$0572	$0F76			INCFSZ	STACK_6, W
;math.ppas,639 :: 		
$0573	$07FA			ADDWF	STACK_10, F
;math.ppas,640 :: 		
$0574	$0877			MOVF	STACK_7, W
;math.ppas,641 :: 		
$0575	$1803			BTFSC	STATUS, C
;math.ppas,642 :: 		
$0576	$0F77			INCFSZ	STACK_7, W
;math.ppas,644 :: 		
$0577	$07FB			ADDWF	STACK_11, F
;math.ppas,645 :: 		
$0578	$	SOK22L8:
;math.ppas,647 :: 		
$0578	$0DF2			RLF	STACK_2, F
;math.ppas,648 :: 		
$0579	$3007			MOVLW	7
;math.ppas,650 :: 		
$057A	$00FC			MOVWF	STACK_12
;math.ppas,651 :: 		
$057B	$	LOOPS3232B:
;math.ppas,652 :: 		
$057B	$0D72			RLF	STACK_2, W
;math.ppas,653 :: 		
$057C	$0DF8			RLF	STACK_8, F
;math.ppas,654 :: 		
$057D	$0DF9			RLF	STACK_9, F
;math.ppas,655 :: 		
$057E	$0DFA			RLF	STACK_10, F
;math.ppas,656 :: 		
$057F	$0DFB			RLF	STACK_11, F
;math.ppas,657 :: 		
$0580	$0874			MOVF	STACK_4, W
;math.ppas,658 :: 		
$0581	$1C72			BTFSS	STACK_2, 0
;math.ppas,660 :: 		
$0582	$2D91			GOTO	SADD22LB
;math.ppas,661 :: 		
$0583	$02F8			SUBWF	STACK_8, F
;math.ppas,662 :: 		
$0584	$0875			MOVF	STACK_5, W
;math.ppas,663 :: 		
$0585	$1C03			BTFSS	STATUS, C
;math.ppas,664 :: 		
$0586	$0F75			INCFSZ	STACK_5, W
;math.ppas,665 :: 		
$0587	$02F9			SUBWF	STACK_9, F
;math.ppas,666 :: 		
$0588	$0876			MOVF	STACK_6, W
;math.ppas,667 :: 		
$0589	$1C03			BTFSS	STATUS, C
;math.ppas,668 :: 		
$058A	$0F76			INCFSZ	STACK_6, W
;math.ppas,669 :: 		
$058B	$02FA			SUBWF	STACK_10, F
;math.ppas,670 :: 		
$058C	$0877			MOVF	STACK_7, W
;math.ppas,671 :: 		
$058D	$1C03			BTFSS	STATUS, C
;math.ppas,672 :: 		
$058E	$0F77			INCFSZ	STACK_7, W
;math.ppas,673 :: 		
$058F	$02FB			SUBWF	STACK_11, F
;math.ppas,675 :: 		
$0590	$2D9E			GOTO	SOK22LB
;math.ppas,676 :: 		
$0591	$	SADD22LB:
;math.ppas,677 :: 		
$0591	$07F8			ADDWF	STACK_8, F
;math.ppas,678 :: 		
$0592	$0875			MOVF	STACK_5, W
;math.ppas,679 :: 		
$0593	$1803			BTFSC	STATUS, C
;math.ppas,680 :: 		
$0594	$0F75			INCFSZ	STACK_5, W
;math.ppas,681 :: 		
$0595	$07F9			ADDWF	STACK_9, F
;math.ppas,682 :: 		
$0596	$0876			MOVF	STACK_6, W
;math.ppas,683 :: 		
$0597	$1803			BTFSC	STATUS, C
;math.ppas,684 :: 		
$0598	$0F76			INCFSZ	STACK_6, W
;math.ppas,685 :: 		
$0599	$07FA			ADDWF	STACK_10, F
;math.ppas,686 :: 		
$059A	$0877			MOVF	STACK_7, W
;math.ppas,687 :: 		
$059B	$1803			BTFSC	STATUS, C
;math.ppas,688 :: 		
$059C	$0F77			INCFSZ	STACK_7, W
;math.ppas,690 :: 		
$059D	$07FB			ADDWF	STACK_11, F
;math.ppas,691 :: 		
$059E	$	SOK22LB:
;math.ppas,693 :: 		
$059E	$0DF2			RLF	STACK_2, F
;math.ppas,694 :: 		
$059F	$0BFC			DECFSZ	STACK_12, F
;math.ppas,696 :: 		
$05A0	$2D7B			GOTO	LOOPS3232B
;math.ppas,697 :: 		
$05A1	$0D71			RLF	STACK_1, W
;math.ppas,698 :: 		
$05A2	$0DF8			RLF	STACK_8, F
;math.ppas,699 :: 		
$05A3	$0DF9			RLF	STACK_9, F
;math.ppas,700 :: 		
$05A4	$0DFA			RLF	STACK_10, F
;math.ppas,701 :: 		
$05A5	$0DFB			RLF	STACK_11, F
;math.ppas,702 :: 		
$05A6	$0874			MOVF	STACK_4, W
;math.ppas,703 :: 		
$05A7	$1C72			BTFSS	STACK_2, 0
;math.ppas,705 :: 		
$05A8	$2DB7			GOTO	SADD22L16
;math.ppas,706 :: 		
$05A9	$02F8			SUBWF	STACK_8, F
;math.ppas,707 :: 		
$05AA	$0875			MOVF	STACK_5, W
;math.ppas,708 :: 		
$05AB	$1C03			BTFSS	STATUS, C
;math.ppas,709 :: 		
$05AC	$0F75			INCFSZ	STACK_5, W
;math.ppas,710 :: 		
$05AD	$02F9			SUBWF	STACK_9, F
;math.ppas,711 :: 		
$05AE	$0876			MOVF	STACK_6, W
;math.ppas,712 :: 		
$05AF	$1C03			BTFSS	STATUS, C
;math.ppas,713 :: 		
$05B0	$0F76			INCFSZ	STACK_6, W
;math.ppas,714 :: 		
$05B1	$02FA			SUBWF	STACK_10, F
;math.ppas,715 :: 		
$05B2	$0877			MOVF	STACK_7, W
;math.ppas,716 :: 		
$05B3	$1C03			BTFSS	STATUS, C
;math.ppas,717 :: 		
$05B4	$0F77			INCFSZ	STACK_7, W
;math.ppas,718 :: 		
$05B5	$02FB			SUBWF	STACK_11, F
;math.ppas,720 :: 		
$05B6	$2DC4			GOTO	SOK22L16
;math.ppas,721 :: 		
$05B7	$	SADD22L16:
;math.ppas,722 :: 		
$05B7	$07F8			ADDWF	STACK_8, F
;math.ppas,723 :: 		
$05B8	$0875			MOVF	STACK_5, W
;math.ppas,724 :: 		
$05B9	$1803			BTFSC	STATUS, C
;math.ppas,725 :: 		
$05BA	$0F75			INCFSZ	STACK_5, W
;math.ppas,726 :: 		
$05BB	$07F9			ADDWF	STACK_9, F
;math.ppas,727 :: 		
$05BC	$0876			MOVF	STACK_6, W
;math.ppas,728 :: 		
$05BD	$1803			BTFSC	STATUS, C
;math.ppas,729 :: 		
$05BE	$0F76			INCFSZ	STACK_6, W
;math.ppas,730 :: 		
$05BF	$07FA			ADDWF	STACK_10, F
;math.ppas,731 :: 		
$05C0	$0877			MOVF	STACK_7, W
;math.ppas,732 :: 		
$05C1	$1803			BTFSC	STATUS, C
;math.ppas,733 :: 		
$05C2	$0F77			INCFSZ	STACK_7, W
;math.ppas,735 :: 		
$05C3	$07FB			ADDWF	STACK_11, F
;math.ppas,736 :: 		
$05C4	$	SOK22L16:
;math.ppas,738 :: 		
$05C4	$0DF1			RLF	STACK_1, F
;math.ppas,739 :: 		
$05C5	$3007			MOVLW	7
;math.ppas,741 :: 		
$05C6	$00FC			MOVWF	STACK_12
;math.ppas,742 :: 		
$05C7	$	LOOPS3232C:
;math.ppas,743 :: 		
$05C7	$0D71			RLF	STACK_1, W
;math.ppas,744 :: 		
$05C8	$0DF8			RLF	STACK_8, F
;math.ppas,745 :: 		
$05C9	$0DF9			RLF	STACK_9, F
;math.ppas,746 :: 		
$05CA	$0DFA			RLF	STACK_10, F
;math.ppas,747 :: 		
$05CB	$0DFB			RLF	STACK_11, F
;math.ppas,748 :: 		
$05CC	$0874			MOVF	STACK_4, W
;math.ppas,749 :: 		
$05CD	$1C71			BTFSS	STACK_1, 0
;math.ppas,751 :: 		
$05CE	$2DDD			GOTO	SADD22LC
;math.ppas,752 :: 		
$05CF	$02F8			SUBWF	STACK_8, F
;math.ppas,753 :: 		
$05D0	$0875			MOVF	STACK_5, W
;math.ppas,754 :: 		
$05D1	$1C03			BTFSS	STATUS, C
;math.ppas,755 :: 		
$05D2	$0F75			INCFSZ	STACK_5, W
;math.ppas,756 :: 		
$05D3	$02F9			SUBWF	STACK_9, F
;math.ppas,757 :: 		
$05D4	$0876			MOVF	STACK_6, W
;math.ppas,758 :: 		
$05D5	$1C03			BTFSS	STATUS, C
;math.ppas,759 :: 		
$05D6	$0F76			INCFSZ	STACK_6, W
;math.ppas,760 :: 		
$05D7	$02FA			SUBWF	STACK_10, F
;math.ppas,761 :: 		
$05D8	$0877			MOVF	STACK_7, W
;math.ppas,762 :: 		
$05D9	$1C03			BTFSS	STATUS, C
;math.ppas,763 :: 		
$05DA	$0F77			INCFSZ	STACK_7, W
;math.ppas,764 :: 		
$05DB	$02FB			SUBWF	STACK_11, F
;math.ppas,766 :: 		
$05DC	$2DEA			GOTO	SOK22LC
;math.ppas,767 :: 		
$05DD	$	SADD22LC:
;math.ppas,768 :: 		
$05DD	$07F8			ADDWF	STACK_8, F
;math.ppas,769 :: 		
$05DE	$0875			MOVF	STACK_5, W
;math.ppas,770 :: 		
$05DF	$1803			BTFSC	STATUS, C
;math.ppas,771 :: 		
$05E0	$0F75			INCFSZ	STACK_5, W
;math.ppas,772 :: 		
$05E1	$07F9			ADDWF	STACK_9, F
;math.ppas,773 :: 		
$05E2	$0876			MOVF	STACK_6, W
;math.ppas,774 :: 		
$05E3	$1803			BTFSC	STATUS, C
;math.ppas,775 :: 		
$05E4	$0F76			INCFSZ	STACK_6, W
;math.ppas,776 :: 		
$05E5	$07FA			ADDWF	STACK_10, F
;math.ppas,777 :: 		
$05E6	$0877			MOVF	STACK_7, W
;math.ppas,778 :: 		
$05E7	$1803			BTFSC	STATUS, C
;math.ppas,779 :: 		
$05E8	$0F77			INCFSZ	STACK_7, W
;math.ppas,781 :: 		
$05E9	$07FB			ADDWF	STACK_11, F
;math.ppas,782 :: 		
$05EA	$	SOK22LC:
;math.ppas,784 :: 		
$05EA	$0DF1			RLF	STACK_1, F
;math.ppas,785 :: 		
$05EB	$0BFC			DECFSZ	STACK_12, F
;math.ppas,787 :: 		
$05EC	$2DC7			GOTO	LOOPS3232C
;math.ppas,788 :: 		
$05ED	$0D70			RLF	STACK_0, W
;math.ppas,789 :: 		
$05EE	$0DF8			RLF	STACK_8, F
;math.ppas,790 :: 		
$05EF	$0DF9			RLF	STACK_9, F
;math.ppas,791 :: 		
$05F0	$0DFA			RLF	STACK_10, F
;math.ppas,792 :: 		
$05F1	$0DFB			RLF	STACK_11, F
;math.ppas,793 :: 		
$05F2	$0874			MOVF	STACK_4, W
;math.ppas,794 :: 		
$05F3	$1C71			BTFSS	STACK_1, 0
;math.ppas,796 :: 		
$05F4	$2E03			GOTO	SADD22L24
;math.ppas,797 :: 		
$05F5	$02F8			SUBWF	STACK_8, F
;math.ppas,798 :: 		
$05F6	$0875			MOVF	STACK_5, W
;math.ppas,799 :: 		
$05F7	$1C03			BTFSS	STATUS, C
;math.ppas,800 :: 		
$05F8	$0F75			INCFSZ	STACK_5, W
;math.ppas,801 :: 		
$05F9	$02F9			SUBWF	STACK_9, F
;math.ppas,802 :: 		
$05FA	$0876			MOVF	STACK_6, W
;math.ppas,803 :: 		
$05FB	$1C03			BTFSS	STATUS, C
;math.ppas,804 :: 		
$05FC	$0F76			INCFSZ	STACK_6, W
;math.ppas,805 :: 		
$05FD	$02FA			SUBWF	STACK_10, F
;math.ppas,806 :: 		
$05FE	$0877			MOVF	STACK_7, W
;math.ppas,807 :: 		
$05FF	$1C03			BTFSS	STATUS, C
;math.ppas,808 :: 		
$0600	$0F77			INCFSZ	STACK_7, W
;math.ppas,809 :: 		
$0601	$02FB			SUBWF	STACK_11, F
;math.ppas,811 :: 		
$0602	$2E10			GOTO	SOK22L24
;math.ppas,812 :: 		
$0603	$	SADD22L24:
;math.ppas,813 :: 		
$0603	$07F8			ADDWF	STACK_8, F
;math.ppas,814 :: 		
$0604	$0875			MOVF	STACK_5, W
;math.ppas,815 :: 		
$0605	$1803			BTFSC	STATUS, C
;math.ppas,816 :: 		
$0606	$0F75			INCFSZ	STACK_5, W
;math.ppas,817 :: 		
$0607	$07F9			ADDWF	STACK_9, F
;math.ppas,818 :: 		
$0608	$0876			MOVF	STACK_6, W
;math.ppas,819 :: 		
$0609	$1803			BTFSC	STATUS, C
;math.ppas,820 :: 		
$060A	$0F76			INCFSZ	STACK_6, W
;math.ppas,821 :: 		
$060B	$07FA			ADDWF	STACK_10, F
;math.ppas,822 :: 		
$060C	$0877			MOVF	STACK_7, W
;math.ppas,823 :: 		
$060D	$1803			BTFSC	STATUS, C
;math.ppas,824 :: 		
$060E	$0F77			INCFSZ	STACK_7, W
;math.ppas,826 :: 		
$060F	$07FB			ADDWF	STACK_11, F
;math.ppas,827 :: 		
$0610	$	SOK22L24:
;math.ppas,829 :: 		
$0610	$0DF0			RLF	STACK_0, F
;math.ppas,830 :: 		
$0611	$3007			MOVLW	7
;math.ppas,832 :: 		
$0612	$00FC			MOVWF	STACK_12
;math.ppas,833 :: 		
$0613	$	LOOPS3232D:
;math.ppas,834 :: 		
$0613	$0D70			RLF	STACK_0, W
;math.ppas,835 :: 		
$0614	$0DF8			RLF	STACK_8, F
;math.ppas,836 :: 		
$0615	$0DF9			RLF	STACK_9, F
;math.ppas,837 :: 		
$0616	$0DFA			RLF	STACK_10, F
;math.ppas,838 :: 		
$0617	$0DFB			RLF	STACK_11, F
;math.ppas,839 :: 		
$0618	$0874			MOVF	STACK_4, W
;math.ppas,840 :: 		
$0619	$1C70			BTFSS	STACK_0, 0
;math.ppas,842 :: 		
$061A	$2E29			GOTO	SADD22LD
;math.ppas,843 :: 		
$061B	$02F8			SUBWF	STACK_8, F
;math.ppas,844 :: 		
$061C	$0875			MOVF	STACK_5, W
;math.ppas,845 :: 		
$061D	$1C03			BTFSS	STATUS, C
;math.ppas,846 :: 		
$061E	$0F75			INCFSZ	STACK_5, W
;math.ppas,847 :: 		
$061F	$02F9			SUBWF	STACK_9, F
;math.ppas,848 :: 		
$0620	$0876			MOVF	STACK_6, W
;math.ppas,849 :: 		
$0621	$1C03			BTFSS	STATUS, C
;math.ppas,850 :: 		
$0622	$0F76			INCFSZ	STACK_6, W
;math.ppas,851 :: 		
$0623	$02FA			SUBWF	STACK_10, F
;math.ppas,852 :: 		
$0624	$0877			MOVF	STACK_7, W
;math.ppas,853 :: 		
$0625	$1C03			BTFSS	STATUS, C
;math.ppas,854 :: 		
$0626	$0F77			INCFSZ	STACK_7, W
;math.ppas,855 :: 		
$0627	$02FB			SUBWF	STACK_11, F
;math.ppas,857 :: 		
$0628	$2E36			GOTO	SOK22LD
;math.ppas,858 :: 		
$0629	$	SADD22LD:
;math.ppas,859 :: 		
$0629	$07F8			ADDWF	STACK_8, F
;math.ppas,860 :: 		
$062A	$0875			MOVF	STACK_5, W
;math.ppas,861 :: 		
$062B	$1803			BTFSC	STATUS, C
;math.ppas,862 :: 		
$062C	$0F75			INCFSZ	STACK_5, W
;math.ppas,863 :: 		
$062D	$07F9			ADDWF	STACK_9, F
;math.ppas,864 :: 		
$062E	$0876			MOVF	STACK_6, W
;math.ppas,865 :: 		
$062F	$1803			BTFSC	STATUS, C
;math.ppas,866 :: 		
$0630	$0F76			INCFSZ	STACK_6, W
;math.ppas,867 :: 		
$0631	$07FA			ADDWF	STACK_10, F
;math.ppas,868 :: 		
$0632	$0877			MOVF	STACK_7, W
;math.ppas,870 :: 		
$0633	$1803			BTFSC	STATUS, C
;math.ppas,871 :: 		
$0634	$0F77			INCFSZ	STACK_7, W
;math.ppas,873 :: 		
$0635	$07FB			ADDWF	STACK_11, F
;math.ppas,874 :: 		
$0636	$	SOK22LD:
;math.ppas,876 :: 		
$0636	$0DF0			RLF	STACK_0, F
;math.ppas,877 :: 		
$0637	$0BFC			DECFSZ	STACK_12, F
;math.ppas,879 :: 		
$0638	$2E13			GOTO	LOOPS3232D
;math.ppas,880 :: 		
$0639	$1870			BTFSC	STACK_0, 0
;math.ppas,881 :: 		
$063A	$2E49			GOTO	SOK22L
;math.ppas,882 :: 		
$063B	$0874			MOVF	STACK_4, W
;math.ppas,883 :: 		
$063C	$07F8			ADDWF	STACK_8, F
;math.ppas,884 :: 		
$063D	$0875			MOVF	STACK_5, W
;math.ppas,885 :: 		
$063E	$1803			BTFSC	STATUS, C
;math.ppas,886 :: 		
$063F	$0F75			INCFSZ	STACK_5, W
;math.ppas,887 :: 		
$0640	$07F9			ADDWF	STACK_9, F
;math.ppas,888 :: 		
$0641	$0876			MOVF	STACK_6, W
;math.ppas,889 :: 		
$0642	$1803			BTFSC	STATUS, C
;math.ppas,890 :: 		
$0643	$0F76			INCFSZ	STACK_6, W
;math.ppas,891 :: 		
$0644	$07FA			ADDWF	STACK_10, F
;math.ppas,892 :: 		
$0645	$0877			MOVF	STACK_7, W
;math.ppas,893 :: 		
$0646	$1803			BTFSC	STATUS, C
;math.ppas,894 :: 		
$0647	$0F77			INCFSZ	STACK_7, W
;math.ppas,895 :: 		
$0648	$07FB			ADDWF	STACK_11, F
;math.ppas,896 :: 		
$0649	$	SOK22L:
;math.ppas,897 :: 		
$0649	$	math_L_9:
;math.ppas,898 :: 		
$0649	$0008			RETURN
$0994	$	_comfrem:
$0994	$1303			BCF	STATUS, RP1
$0995	$1283			BCF	STATUS, RP0
;math.ppas,901 :: 		
;math.ppas,903 :: 		
$0996	$09FB			COMF	STACK_11, F
;math.ppas,904 :: 		
$0997	$09FA			COMF	STACK_10, F
;math.ppas,905 :: 		
$0998	$09F9			COMF	STACK_9, F
;math.ppas,906 :: 		
$0999	$09F8			COMF	STACK_8, F
;math.ppas,907 :: 		
$099A	$0AF8			INCF	STACK_8, F
;math.ppas,908 :: 		
$099B	$1903			BTFSC	STATUS, Z
;math.ppas,909 :: 		
$099C	$0AF9			INCF	STACK_9, F
;math.ppas,910 :: 		
$099D	$1903			BTFSC	STATUS, Z
;math.ppas,911 :: 		
$099E	$0AFA			INCF	STACK_10, F
;math.ppas,912 :: 		
$099F	$1903			BTFSC	STATUS, Z
;math.ppas,913 :: 		
$09A0	$0AFB			INCF	STACK_11, F
;math.ppas,914 :: 		
$09A1	$	math_L_10:
;math.ppas,915 :: 		
$09A1	$0008			RETURN
$0959	$	_usart_write_text:
;USART_c67.ppas,121 :: 		
;USART_c67.ppas,122 :: 		
$0959	$1303			BCF	STATUS, RP1
$095A	$1283			BCF	STATUS, RP0
$095B	$01D7			CLRF	_usart_write_text_local_i, 1
;USART_c67.ppas,123 :: 		
$095C	$0856			MOVF	FARG_Usart_Write_Text, 0
$095D	$0084			MOVWF	FSR
$095E	$0800			MOVF	INDF, 0
$095F	$00D8			MOVWF	_usart_write_text_local_data
;USART_c67.ppas,124 :: 		
$0960	$	USART_c67_L_47:
$0960	$0858			MOVF	_usart_write_text_local_data, 0
$0961	$3A00			XORLW	0
$0962	$1903			BTFSC	STATUS, Z
$0963	$296E			GOTO	USART_c67_L_48
;USART_c67.ppas,126 :: 		
$0964	$0858			MOVF	_usart_write_text_local_data, 0
$0965	$00DD			MOVWF	FARG_USART_Write
$0966	$2182			CALL	_usart_write
;USART_c67.ppas,127 :: 		
$0967	$0AD7			INCF	_usart_write_text_local_i, 1
;USART_c67.ppas,128 :: 		
$0968	$0857			MOVF	_usart_write_text_local_i, 0
$0969	$0756			ADDWF	FARG_Usart_Write_Text, 0
$096A	$0084			MOVWF	FSR
$096B	$0800			MOVF	INDF, 0
$096C	$00D8			MOVWF	_usart_write_text_local_data
;USART_c67.ppas,129 :: 		
$096D	$2960			GOTO	USART_c67_L_47
$096E	$	USART_c67_L_48:
$096E	$	USART_c67_L_45:
;USART_c67.ppas,130 :: 		
$096E	$0008			RETURN
$0800	$	_usart_read_text:
;USART_c67.ppas,78 :: 		
;USART_c67.ppas,79 :: 		
$0800	$1303			BCF	STATUS, RP1
$0801	$1283			BCF	STATUS, RP0
$0802	$01D8			CLRF	_usart_read_text_local_i, 1
;USART_c67.ppas,80 :: 		
$0803	$01D9			CLRF	_usart_read_text_local_j, 1
;USART_c67.ppas,81 :: 		
$0804	$01DC			CLRF	_usart_read_text_local_lasti, 1
;USART_c67.ppas,82 :: 		
$0805	$0857			MOVF	FARG_Usart_Read_Text+1, 0
$0806	$0084			MOVWF	FSR
$0807	$0800			MOVF	INDF, 0
$0808	$00DB			MOVWF	_usart_read_text_local_data2
;USART_c67.ppas,83 :: 		
$0809	$	USART_c67_L_29:
;USART_c67.ppas,85 :: 		
$0809	$21A2			CALL	_usart_data_ready
$080A	$0870			MOVF	STACK_0, 0
$080B	$3A00			XORLW	0
$080C	$1903			BTFSC	STATUS, Z
$080D	$2839			GOTO	USART_c67_L_34
$080E	$	USART_c67_L_33:
;USART_c67.ppas,87 :: 		
$080E	$216F			CALL	_usart_read
$080F	$0870			MOVF	STACK_0, 0
$0810	$00DA			MOVWF	_usart_read_text_local_data
;USART_c67.ppas,88 :: 		
$0811	$0858			MOVF	_usart_read_text_local_i, 0
$0812	$0756			ADDWF	FARG_Usart_Read_Text, 0
$0813	$00F1			MOVWF	STACK_1
$0814	$0871			MOVF	STACK_1, 0
$0815	$0084			MOVWF	FSR
$0816	$0871			MOVF	STACK_1, 0
$0817	$0084			MOVWF	FSR
$0818	$0870			MOVF	STACK_0, 0
$0819	$0080			MOVWF	INDF
;USART_c67.ppas,89 :: 		
$081A	$085A			MOVF	_usart_read_text_local_data, 0
$081B	$065B			XORWF	_usart_read_text_local_data2, 0
$081C	$1D03			BTFSS	STATUS, Z
$081D	$2823			GOTO	USART_c67_L_37
$081E	$	USART_c67_L_36:
;USART_c67.ppas,91 :: 		
$081E	$0859			MOVF	_usart_read_text_local_j, 0
$081F	$0258			SUBWF	_usart_read_text_local_i, 0
$0820	$00DC			MOVWF	_usart_read_text_local_lasti
;USART_c67.ppas,92 :: 		
$0821	$0AD9			INCF	_usart_read_text_local_j, 1
;USART_c67.ppas,93 :: 		
$0822	$2825			GOTO	USART_c67_L_38
;USART_c67.ppas,94 :: 		
$0823	$	USART_c67_L_37:
;USART_c67.ppas,96 :: 		
$0823	$01D9			CLRF	_usart_read_text_local_j, 1
;USART_c67.ppas,97 :: 		
$0824	$01DC			CLRF	_usart_read_text_local_lasti, 1
;USART_c67.ppas,98 :: 		
$0825	$	USART_c67_L_38:
;USART_c67.ppas,100 :: 		
$0825	$0859			MOVF	_usart_read_text_local_j, 0
$0826	$0757			ADDWF	FARG_Usart_Read_Text+1, 0
$0827	$0084			MOVWF	FSR
$0828	$0800			MOVF	INDF, 0
$0829	$00F1			MOVWF	STACK_1
$082A	$0871			MOVF	STACK_1, 0
$082B	$00DB			MOVWF	_usart_read_text_local_data2
;USART_c67.ppas,102 :: 		
$082C	$0871			MOVF	STACK_1, 0
$082D	$3A00			XORLW	0
$082E	$1D03			BTFSS	STATUS, Z
$082F	$2831			GOTO	USART_c67_L_40
$0830	$	USART_c67_L_39:
;USART_c67.ppas,103 :: 		
$0830	$283A			GOTO	USART_c67_L_30
$0831	$	USART_c67_L_40:
$0831	$	USART_c67_L_41:
;USART_c67.ppas,105 :: 		
$0831	$0AD8			INCF	_usart_read_text_local_i, 1
;USART_c67.ppas,106 :: 		
$0832	$0858			MOVF	_usart_read_text_local_i, 0
$0833	$3C14			SUBLW	20
$0834	$1803			BTFSC	STATUS, C
$0835	$2839			GOTO	USART_c67_L_43
$0836	$	USART_c67_L_42:
;USART_c67.ppas,108 :: 		
$0836	$3013			MOVLW	19
$0837	$00DC			MOVWF	_usart_read_text_local_lasti
;USART_c67.ppas,109 :: 		
$0838	$283A			GOTO	USART_c67_L_30
;USART_c67.ppas,110 :: 		
$0839	$	USART_c67_L_43:
$0839	$	USART_c67_L_44:
;USART_c67.ppas,111 :: 		
$0839	$	USART_c67_L_34:
$0839	$	USART_c67_L_35:
;USART_c67.ppas,112 :: 		
$0839	$2809			GOTO	USART_c67_L_29
$083A	$	USART_c67_L_30:
;USART_c67.ppas,113 :: 		
$083A	$085C			MOVF	_usart_read_text_local_lasti, 0
$083B	$0756			ADDWF	FARG_Usart_Read_Text, 0
$083C	$00F0			MOVWF	STACK_0
$083D	$0870			MOVF	STACK_0, 0
$083E	$0084			MOVWF	FSR
$083F	$0870			MOVF	STACK_0, 0
$0840	$0084			MOVWF	FSR
$0841	$0180			CLRF	INDF, 1
$0842	$	USART_c67_L_27:
;USART_c67.ppas,114 :: 		
$0842	$0008			RETURN
$0843	$	_strcmp:
;StringsLib.ppas,172 :: 		
;StringsLib.ppas,173 :: 		
$0843	$1303			BCF	STATUS, RP1
$0844	$1283			BCF	STATUS, RP0
$0845	$01DA			CLRF	_strcmp_local_i, 1
;StringsLib.ppas,174 :: 		
$0846	$0856			MOVF	FARG_strcmp, 0
$0847	$0084			MOVWF	FSR
$0848	$0800			MOVF	INDF, 0
$0849	$00D8			MOVWF	_strcmp_local_result
$084A	$01D9			CLRF	_strcmp_local_result+1
;StringsLib.ppas,175 :: 		
$084B	$0857			MOVF	FARG_strcmp+1, 0
$084C	$0084			MOVWF	FSR
$084D	$0800			MOVF	INDF, 0
$084E	$00F0			MOVWF	STACK_0
;StringsLib.ppas,176 :: 		
$084F	$3000			MOVLW	0
$0850	$00D9			MOVWF	_strcmp_local_result+1
$0851	$0870			MOVF	STACK_0, 0
$0852	$02D8			SUBWF	_strcmp_local_result, 1
$0853	$1C03			BTFSS	STATUS, C
$0854	$03D9			DECF	_strcmp_local_result+1, 1
;StringsLib.ppas,177 :: 		
$0855	$	StringsLib_L_77:
$0855	$3000			MOVLW	0
$0856	$0659			XORWF	_strcmp_local_result+1, 0
$0857	$1D03			BTFSS	STATUS, Z
$0858	$285B			GOTO	L_strcmp_8
$0859	$3000			MOVLW	0
$085A	$0658			XORWF	_strcmp_local_result, 0
$085B	$	L_strcmp_8:
$085B	$30FF			MOVLW	255
$085C	$1D03			BTFSS	STATUS, Z
$085D	$3000			MOVLW	0
$085E	$00F3			MOVWF	STACK_3
$085F	$085A			MOVF	_strcmp_local_i, 0
$0860	$0756			ADDWF	FARG_strcmp, 0
$0861	$0084			MOVWF	FSR
$0862	$0800			MOVF	INDF, 0
$0863	$00F2			MOVWF	STACK_2
$0864	$0872			MOVF	STACK_2, 0
$0865	$3A00			XORLW	0
$0866	$30FF			MOVLW	255
$0867	$1903			BTFSC	STATUS, Z
$0868	$3000			MOVLW	0
$0869	$00F0			MOVWF	STACK_0
$086A	$0873			MOVF	STACK_3, 0
$086B	$05F0			ANDWF	STACK_0, 1
$086C	$1903			BTFSC	STATUS, Z
$086D	$2884			GOTO	StringsLib_L_78
;StringsLib.ppas,179 :: 		
$086E	$0A5A			INCF	_strcmp_local_i, 0
$086F	$00F0			MOVWF	STACK_0
$0870	$0870			MOVF	STACK_0, 0
$0871	$00DA			MOVWF	_strcmp_local_i
;StringsLib.ppas,180 :: 		
$0872	$0870			MOVF	STACK_0, 0
$0873	$0756			ADDWF	FARG_strcmp, 0
$0874	$0084			MOVWF	FSR
$0875	$0800			MOVF	INDF, 0
$0876	$00D8			MOVWF	_strcmp_local_result
$0877	$01D9			CLRF	_strcmp_local_result+1
;StringsLib.ppas,181 :: 		
$0878	$0870			MOVF	STACK_0, 0
$0879	$0757			ADDWF	FARG_strcmp+1, 0
$087A	$0084			MOVWF	FSR
$087B	$0800			MOVF	INDF, 0
$087C	$00F0			MOVWF	STACK_0
;StringsLib.ppas,182 :: 		
$087D	$3000			MOVLW	0
$087E	$00D9			MOVWF	_strcmp_local_result+1
$087F	$0870			MOVF	STACK_0, 0
$0880	$02D8			SUBWF	_strcmp_local_result, 1
$0881	$1C03			BTFSS	STATUS, C
$0882	$03D9			DECF	_strcmp_local_result+1, 1
;StringsLib.ppas,183 :: 		
$0883	$2855			GOTO	StringsLib_L_77
$0884	$	StringsLib_L_78:
$0884	$	StringsLib_L_75:
;StringsLib.ppas,184 :: 		
$0884	$0858			MOVF	_strcmp_local_result, 0
$0885	$00F0			MOVWF	STACK_0
$0886	$0859			MOVF	_strcmp_local_result+1, 0
$0887	$00F1			MOVWF	STACK_0+1
$0888	$0008			RETURN
$0889	$	_adc_read:
;ADClib_A_C.ppas,12 :: 		
;ADClib_A_C.ppas,13 :: 		
$0889	$1303			BCF	STATUS, RP1
$088A	$1283			BCF	STATUS, RP0
$088B	$019F			CLRF	ADCON0, 1
;ADClib_A_C.ppas,14 :: 		
$088C	$30C0			MOVLW	192
$088D	$049F			IORWF	ADCON0, 1
;ADClib_A_C.ppas,15 :: 		
$088E	$3040			MOVLW	64
$088F	$1683			BSF	STATUS, RP0
$0890	$041F			IORWF	ADCON1, 0
$0891	$00F0			MOVWF	STACK_0
$0892	$0870			MOVF	STACK_0, 0
$0893	$009F			MOVWF	ADCON1
;ADClib_A_C.ppas,17 :: 		
$0894	$3080			MOVLW	128
$0895	$0470			IORWF	STACK_0, 0
$0896	$009F			MOVWF	ADCON1
;ADClib_A_C.ppas,18 :: 		
$0897	$1283			BCF	STATUS, RP0
$0898	$0856			MOVF	FARG_ADC_read, 0
$0899	$00F0			MOVWF	STACK_0
$089A	$0DF0			RLF	STACK_0, 1
$089B	$1070			BCF	STACK_0, 0
$089C	$0DF0			RLF	STACK_0, 1
$089D	$1070			BCF	STACK_0, 0
$089E	$0DF0			RLF	STACK_0, 1
$089F	$1070			BCF	STACK_0, 0
$08A0	$0870			MOVF	STACK_0, 0
$08A1	$049F			IORWF	ADCON0, 1
;ADClib_A_C.ppas,19 :: 		
$08A2	$141F			BSF	ADCON0, 0
;ADClib_A_C.ppas,20 :: 		
$08A3	$21AF			CALL	_delay_22us
;ADClib_A_C.ppas,21 :: 		
$08A4	$151F			BSF	ADCON0, 2
;ADClib_A_C.ppas,22 :: 		
$08A5	$	ADClib_A_C_L_2:
$08A5	$081F			MOVF	ADCON0, 0
$08A6	$00F2			MOVWF	STACK_2
$08A7	$3000			MOVLW	0
$08A8	$1972			BTFSC	STACK_2, 2
$08A9	$3001			MOVLW	1
$08AA	$00F2			MOVWF	STACK_2
$08AB	$0872			MOVF	STACK_2, 0
$08AC	$3A01			XORLW	1
$08AD	$1D03			BTFSS	STATUS, Z
$08AE	$28B1			GOTO	ADClib_A_C_L_3
;ADClib_A_C.ppas,23 :: 		
$08AF	$0000			NOP
$08B0	$28A5			GOTO	ADClib_A_C_L_2
$08B1	$	ADClib_A_C_L_3:
;ADClib_A_C.ppas,24 :: 		
$08B1	$081E			MOVF	ADRESH, 0
$08B2	$00F2			MOVWF	STACK_2
$08B3	$01F3			CLRF	STACK_2+1
$08B4	$0872			MOVF	STACK_2, 0
$08B5	$00F3			MOVWF	STACK_2+1
$08B6	$01F2			CLRF	STACK_2
$08B7	$0872			MOVF	STACK_2, 0
$08B8	$00D7			MOVWF	_adc_read_local_result
$08B9	$0873			MOVF	STACK_2+1, 0
$08BA	$00D8			MOVWF	_adc_read_local_result+1
;ADClib_A_C.ppas,25 :: 		
$08BB	$1683			BSF	STATUS, RP0
$08BC	$081E			MOVF	ADRESL, 0
$08BD	$0472			IORWF	STACK_2, 0
$08BE	$1283			BCF	STATUS, RP0
$08BF	$00D7			MOVWF	_adc_read_local_result
$08C0	$0873			MOVF	STACK_2+1, 0
$08C1	$00D8			MOVWF	_adc_read_local_result+1
$08C2	$3000			MOVLW	0
$08C3	$04D8			IORWF	_adc_read_local_result+1, 1
;ADClib_A_C.ppas,26 :: 		
$08C4	$101F			BCF	ADCON0, 0
$08C5	$	ADClib_A_C_L_0:
;ADClib_A_C.ppas,27 :: 		
$08C5	$0857			MOVF	_adc_read_local_result, 0
$08C6	$00F0			MOVWF	STACK_0
$08C7	$0858			MOVF	_adc_read_local_result+1, 0
$08C8	$00F1			MOVWF	STACK_0+1
$08C9	$0008			RETURN
$06E6	$	_wordtostr:
;conv.ppas,31 :: 		
;conv.ppas,32 :: 		
$06E6	$3001			MOVLW	1
$06E7	$1303			BCF	STATUS, RP1
$06E8	$1283			BCF	STATUS, RP0
$06E9	$00D9			MOVWF	_wordtostr_local_len
;conv.ppas,33 :: 		
$06EA	$0857			MOVF	FARG_WordToStr+1, 0
$06EB	$3C00			SUBLW	0
$06EC	$1D03			BTFSS	STATUS, Z
$06ED	$2EF0			GOTO	L_WordToStr_0
$06EE	$0856			MOVF	FARG_WordToStr, 0
$06EF	$3C09			SUBLW	9
$06F0	$	L_WordToStr_0:
$06F0	$1803			BTFSC	STATUS, C
$06F1	$2EF3			GOTO	conv_L_15
$06F2	$	conv_L_14:
;conv.ppas,34 :: 		
$06F2	$0AD9			INCF	_wordtostr_local_len, 1
$06F3	$	conv_L_15:
$06F3	$	conv_L_16:
;conv.ppas,35 :: 		
$06F3	$0857			MOVF	FARG_WordToStr+1, 0
$06F4	$3C00			SUBLW	0
$06F5	$1D03			BTFSS	STATUS, Z
$06F6	$2EF9			GOTO	L_WordToStr_1
$06F7	$0856			MOVF	FARG_WordToStr, 0
$06F8	$3C63			SUBLW	99
$06F9	$	L_WordToStr_1:
$06F9	$1803			BTFSC	STATUS, C
$06FA	$2EFC			GOTO	conv_L_18
$06FB	$	conv_L_17:
;conv.ppas,36 :: 		
$06FB	$0AD9			INCF	_wordtostr_local_len, 1
$06FC	$	conv_L_18:
$06FC	$	conv_L_19:
;conv.ppas,37 :: 		
$06FC	$0857			MOVF	FARG_WordToStr+1, 0
$06FD	$3C03			SUBLW	3
$06FE	$1D03			BTFSS	STATUS, Z
$06FF	$2F02			GOTO	L_WordToStr_2
$0700	$0856			MOVF	FARG_WordToStr, 0
$0701	$3CE7			SUBLW	231
$0702	$	L_WordToStr_2:
$0702	$1803			BTFSC	STATUS, C
$0703	$2F05			GOTO	conv_L_21
$0704	$	conv_L_20:
;conv.ppas,38 :: 		
$0704	$0AD9			INCF	_wordtostr_local_len, 1
$0705	$	conv_L_21:
$0705	$	conv_L_22:
;conv.ppas,39 :: 		
$0705	$0857			MOVF	FARG_WordToStr+1, 0
$0706	$3C27			SUBLW	39
$0707	$1D03			BTFSS	STATUS, Z
$0708	$2F0B			GOTO	L_WordToStr_3
$0709	$0856			MOVF	FARG_WordToStr, 0
$070A	$3C0F			SUBLW	15
$070B	$	L_WordToStr_3:
$070B	$1803			BTFSC	STATUS, C
$070C	$2F0E			GOTO	conv_L_24
$070D	$	conv_L_23:
;conv.ppas,40 :: 		
$070D	$0AD9			INCF	_wordtostr_local_len, 1
$070E	$	conv_L_24:
$070E	$	conv_L_25:
;conv.ppas,41 :: 		
$070E	$0858			MOVF	FARG_WordToStr+2, 0
$070F	$0084			MOVWF	FSR
$0710	$3020			MOVLW	32
$0711	$0080			MOVWF	INDF
$0712	$0A84			INCF	FSR, 1
$0713	$0080			MOVWF	INDF
$0714	$0A84			INCF	FSR, 1
$0715	$0080			MOVWF	INDF
$0716	$0A84			INCF	FSR, 1
$0717	$0080			MOVWF	INDF
$0718	$0A84			INCF	FSR, 1
$0719	$0080			MOVWF	INDF
$071A	$0A84			INCF	FSR, 1
$071B	$0180			CLRF	INDF
;conv.ppas,42 :: 		
$071C	$0384			DECF	FSR, 1
;conv.ppas,43 :: 		
$071D	$	conv_L_28:
$071D	$0859			MOVF	_wordtostr_local_len, 0
$071E	$3C00			SUBLW	0
$071F	$1803			BTFSC	STATUS, C
$0720	$2F43			GOTO	conv_L_29
;conv.ppas,45 :: 		
$0721	$300A			MOVLW	10
$0722	$00F4			MOVWF	STACK_4
$0723	$01F5			CLRF	STACK_4+1
$0724	$0856			MOVF	FARG_WordToStr, 0
$0725	$00F0			MOVWF	STACK_0
$0726	$0857			MOVF	FARG_WordToStr+1, 0
$0727	$00F1			MOVWF	STACK_0+1
$0728	$158A			BSF	PCLATH, 3
$0729	$213C			CALL	_div_16x16_u
$072A	$118A			BCF	PCLATH, 3
$072B	$0878			MOVF	STACK_8, 0
$072C	$00F0			MOVWF	STACK_0
$072D	$0879			MOVF	STACK_9, 0
$072E	$00F1			MOVWF	STACK_1
$072F	$3030			MOVLW	48
$0730	$0770			ADDWF	STACK_0, 0
$0731	$0080			MOVWF	INDF
;conv.ppas,46 :: 		
;conv.ppas,47 :: 		
$0732	$0384			DECF	FSR, 1
;conv.ppas,48 :: 		
$0733	$300A			MOVLW	10
$0734	$00F4			MOVWF	STACK_4
$0735	$01F5			CLRF	STACK_4+1
$0736	$0856			MOVF	FARG_WordToStr, 0
$0737	$00F0			MOVWF	STACK_0
$0738	$0857			MOVF	FARG_WordToStr+1, 0
$0739	$00F1			MOVWF	STACK_0+1
$073A	$158A			BSF	PCLATH, 3
$073B	$213C			CALL	_div_16x16_u
$073C	$118A			BCF	PCLATH, 3
$073D	$0870			MOVF	STACK_0, 0
$073E	$00D6			MOVWF	FARG_WordToStr
$073F	$0871			MOVF	STACK_0+1, 0
$0740	$00D7			MOVWF	FARG_WordToStr+1
;conv.ppas,49 :: 		
$0741	$03D9			DECF	_wordtostr_local_len, 1
;conv.ppas,50 :: 		
$0742	$2F1D			GOTO	conv_L_28
$0743	$	conv_L_29:
$0743	$	conv_L_13:
;conv.ppas,51 :: 		
$0743	$0008			RETURN
$0744	$	_usart_init:
;USART_c67.ppas,22 :: 		
;USART_c67.ppas,24 :: 		
$0744	$	USART_c67_L_1:
$0744	$1303			BCF	STATUS, RP1
$0745	$1683			BSF	STATUS, RP0
$0746	$1698			BSF	TXSTA, 5
$0747	$	USART_c67_L_2:
;USART_c67.ppas,25 :: 		
$0747	$3090			MOVLW	144
$0748	$1283			BCF	STATUS, RP0
$0749	$0098			MOVWF	RCSTA
;USART_c67.ppas,31 :: 		
$074A	$	USART_c67_L_3:
$074A	$1683			BSF	STATUS, RP0
$074B	$1787			BSF	TRISC, 7
$074C	$	USART_c67_L_4:
;USART_c67.ppas,32 :: 		
$074C	$1307			BCF	TRISC, 6
$074D	$	USART_c67_L_6:
;USART_c67.ppas,35 :: 		
$074D	$	USART_c67_L_8:
$074D	$1283			BCF	STATUS, RP0
$074E	$080C			MOVF	PIR1, 0
$074F	$00F1			MOVWF	STACK_1
$0750	$3000			MOVLW	0
$0751	$1AF1			BTFSC	STACK_1, 5
$0752	$3001			MOVLW	1
$0753	$00F1			MOVWF	STACK_1
$0754	$0871			MOVF	STACK_1, 0
$0755	$3A01			XORLW	1
$0756	$1903			BTFSC	STATUS, Z
$0757	$2F4D			GOTO	USART_c67_L_8
;USART_c67.ppas,36 :: 		
$0758	$	USART_c67_L_9:
$0758	$	USART_c67_L_0:
;USART_c67.ppas,37 :: 		
$0758	$0008			RETURN
$08CA	$	_mul_32x32_s:
$08CA	$1303			BCF	STATUS, RP1
$08CB	$1283			BCF	STATUS, RP0
;math.ppas,1675 :: 		
;math.ppas,1680 :: 		
$08CC	$01FD			CLRF	STACK_13
;math.ppas,1683 :: 		
$08CD	$	_IF_FIRST:
;math.ppas,1684 :: 		
$08CD	$1FF3			BTFSS	STACK_3, 7
;math.ppas,1686 :: 		
$08CE	$28DC			GOTO	_IF_SECOND
;math.ppas,1691 :: 		
$08CF	$	_INVERCE_FIRST:
;math.ppas,1692 :: 		
$08CF	$09F0			COMF	STACK_0, F
;math.ppas,1693 :: 		
$08D0	$09F1			COMF	STACK_1, F
;math.ppas,1694 :: 		
$08D1	$09F2			COMF	STACK_2, F
;math.ppas,1701 :: 		
$08D2	$09F3			COMF	STACK_3, F
;math.ppas,1702 :: 		
$08D3	$0AF0			INCF	STACK_0, F
;math.ppas,1703 :: 		
$08D4	$1903			BTFSC	STATUS, Z
;math.ppas,1704 :: 		
$08D5	$0AF1			INCF	STACK_1, F
;math.ppas,1705 :: 		
$08D6	$1903			BTFSC	STATUS, Z
;math.ppas,1706 :: 		
$08D7	$0AF2			INCF	STACK_2, F
;math.ppas,1707 :: 		
$08D8	$1903			BTFSC	STATUS, Z
;math.ppas,1708 :: 		
$08D9	$0AF3			INCF	STACK_3, F
;math.ppas,1709 :: 		
$08DA	$3081			MOVLW	129
;math.ppas,1711 :: 		
$08DB	$07FD			ADDWF	STACK_13, F
;math.ppas,1714 :: 		
$08DC	$	_IF_SECOND:
;math.ppas,1715 :: 		
$08DC	$1FF7			BTFSS	STACK_7, 7
;math.ppas,1717 :: 		
$08DD	$28EA			GOTO	_MULT
;math.ppas,1722 :: 		
$08DE	$	_INBERSE_SECOND:
;math.ppas,1723 :: 		
$08DE	$09F4			COMF	STACK_4, F
;math.ppas,1724 :: 		
$08DF	$09F5			COMF	STACK_5, F
;math.ppas,1725 :: 		
$08E0	$09F6			COMF	STACK_6, F
;math.ppas,1732 :: 		
$08E1	$09F7			COMF	STACK_7, F
;math.ppas,1733 :: 		
$08E2	$0AF4			INCF	STACK_4, F
;math.ppas,1734 :: 		
$08E3	$1903			BTFSC	STATUS, Z
;math.ppas,1735 :: 		
$08E4	$0AF5			INCF	STACK_5, F
;math.ppas,1736 :: 		
$08E5	$1903			BTFSC	STATUS, Z
;math.ppas,1737 :: 		
$08E6	$0AF6			INCF	STACK_6, F
;math.ppas,1738 :: 		
$08E7	$1903			BTFSC	STATUS, Z
;math.ppas,1739 :: 		
$08E8	$0AF7			INCF	STACK_7, F
;math.ppas,1741 :: 		
$08E9	$0AFD			INCF	STACK_13, F
;math.ppas,1742 :: 		
$08EA	$	_MULT:
;math.ppas,1744 :: 		
$08EA	$2105			CALL	_mul_32x32_u
;math.ppas,1748 :: 		
$08EB	$1C7D			BTFSS	STACK_13, 0
;math.ppas,1754 :: 		
$08EC	$2904			GOTO	_EXIT
;math.ppas,1755 :: 		
$08ED	$09F0			COMF	STACK_0, F
;math.ppas,1756 :: 		
$08EE	$09F1			COMF	STACK_1, F
;math.ppas,1757 :: 		
$08EF	$09F2			COMF	STACK_2, F
;math.ppas,1763 :: 		
$08F0	$09F3			COMF	STACK_3, F
;math.ppas,1764 :: 		
$08F1	$09F8			COMF	STACK_8, F
;math.ppas,1765 :: 		
$08F2	$09F9			COMF	STACK_9, F
;math.ppas,1766 :: 		
$08F3	$09FA			COMF	STACK_10, F
;math.ppas,1776 :: 		
$08F4	$09FB			COMF	STACK_11, F
;math.ppas,1777 :: 		
$08F5	$0AF0			INCF	STACK_0, F
;math.ppas,1778 :: 		
$08F6	$1903			BTFSC	STATUS, Z
;math.ppas,1779 :: 		
$08F7	$0AF1			INCF	STACK_1, F
;math.ppas,1780 :: 		
$08F8	$1903			BTFSC	STATUS, Z
;math.ppas,1781 :: 		
$08F9	$0AF2			INCF	STACK_2, F
;math.ppas,1782 :: 		
$08FA	$1903			BTFSC	STATUS, Z
;math.ppas,1783 :: 		
$08FB	$0AF3			INCF	STACK_3, F
;math.ppas,1784 :: 		
$08FC	$1903			BTFSC	STATUS, Z
;math.ppas,1785 :: 		
$08FD	$0AF8			INCF	STACK_8, F
;math.ppas,1786 :: 		
$08FE	$1903			BTFSC	STATUS, Z
;math.ppas,1787 :: 		
$08FF	$0AF9			INCF	STACK_9, F
;math.ppas,1788 :: 		
$0900	$1903			BTFSC	STATUS, Z
;math.ppas,1789 :: 		
$0901	$0AFA			INCF	STACK_10, F
;math.ppas,1790 :: 		
$0902	$1903			BTFSC	STATUS, Z
;math.ppas,1791 :: 		
$0903	$0AFB			INCF	STACK_11, F
;math.ppas,1792 :: 		
$0904	$	_EXIT:
;math.ppas,1793 :: 		
$0904	$	math_L_14:
;math.ppas,1794 :: 		
$0904	$0008			RETURN
$064A	$	_div_32x32_s:
$064A	$1303			BCF	STATUS, RP1
$064B	$1283			BCF	STATUS, RP0
;math.ppas,925 :: 		
;math.ppas,928 :: 		
$064C	$	FXD3232S:
;math.ppas,929 :: 		
$064C	$01FC			CLRF	STACK_12
;math.ppas,930 :: 		
$064D	$1BF7			BTFSC	STACK_7, 7
;math.ppas,932 :: 		
$064E	$0AFC			INCF	STACK_12, F
;math.ppas,933 :: 		
$064F	$01FD			CLRF	STACK_13
;math.ppas,934 :: 		
$0650	$01FB			CLRF	STACK_11
;math.ppas,935 :: 		
$0651	$01FA			CLRF	STACK_10
;math.ppas,936 :: 		
$0652	$01F9			CLRF	STACK_9
;math.ppas,937 :: 		
$0653	$01F8			CLRF	STACK_8
;math.ppas,938 :: 		
$0654	$0873			MOVF	STACK_3, W
;math.ppas,939 :: 		
$0655	$0472			IORWF	STACK_2, W
;math.ppas,940 :: 		
$0656	$0471			IORWF	STACK_1, W
;math.ppas,941 :: 		
$0657	$0470			IORWF	STACK_0, W
;math.ppas,942 :: 		
$0658	$1903			BTFSC	STATUS, Z
;math.ppas,943 :: 		
$0659	$2EDE			GOTO	END_ALL
;math.ppas,944 :: 		
$065A	$0873			MOVF	STACK_3, W
;math.ppas,945 :: 		
$065B	$0677			XORWF	STACK_7, W
;math.ppas,946 :: 		
$065C	$00A0			MOVWF	MATH___MATH_TEMPB
;math.ppas,947 :: 		
$065D	$1BA0			BTFSC	MATH___MATH_TEMPB, 7
;math.ppas,951 :: 		
$065E	$09FD			COMF	STACK_13, F
;math.ppas,952 :: 		
$065F	$1FF7			BTFSS	STACK_7, 7
;math.ppas,954 :: 		
$0660	$2E6C			GOTO	CA3232S
;math.ppas,955 :: 		
$0661	$09F4			COMF	STACK_4, F
;math.ppas,956 :: 		
$0662	$09F5			COMF	STACK_5, F
;math.ppas,957 :: 		
$0663	$09F6			COMF	STACK_6, F
;math.ppas,958 :: 		
$0664	$09F7			COMF	STACK_7, F
;math.ppas,959 :: 		
$0665	$0AF4			INCF	STACK_4, F
;math.ppas,960 :: 		
$0666	$1903			BTFSC	STATUS, Z
;math.ppas,961 :: 		
$0667	$0AF5			INCF	STACK_5, F
;math.ppas,962 :: 		
$0668	$1903			BTFSC	STATUS, Z
;math.ppas,963 :: 		
$0669	$0AF6			INCF	STACK_6, F
;math.ppas,964 :: 		
$066A	$1903			BTFSC	STATUS, Z
;math.ppas,966 :: 		
$066B	$0AF7			INCF	STACK_7, F
;math.ppas,967 :: 		
$066C	$	CA3232S:
;math.ppas,968 :: 		
$066C	$1FF3			BTFSS	STACK_3, 7
;math.ppas,970 :: 		
$066D	$2E79			GOTO	C3232SX
;math.ppas,971 :: 		
$066E	$09F0			COMF	STACK_0, F
;math.ppas,972 :: 		
$066F	$09F1			COMF	STACK_1, F
;math.ppas,973 :: 		
$0670	$09F2			COMF	STACK_2, F
;math.ppas,974 :: 		
$0671	$09F3			COMF	STACK_3, F
;math.ppas,975 :: 		
$0672	$0AF0			INCF	STACK_0, F
;math.ppas,976 :: 		
$0673	$1903			BTFSC	STATUS, Z
;math.ppas,977 :: 		
$0674	$0AF1			INCF	STACK_1, F
;math.ppas,978 :: 		
$0675	$1903			BTFSC	STATUS, Z
;math.ppas,979 :: 		
$0676	$0AF2			INCF	STACK_2, F
;math.ppas,980 :: 		
$0677	$1903			BTFSC	STATUS, Z
;math.ppas,982 :: 		
$0678	$0AF3			INCF	STACK_3, F
;math.ppas,983 :: 		
$0679	$	C3232SX:
;math.ppas,984 :: 		
$0679	$0873			MOVF	STACK_3, W
;math.ppas,985 :: 		
$067A	$0477			IORWF	STACK_7, W
;math.ppas,986 :: 		
$067B	$00A0			MOVWF	MATH___MATH_TEMPB
;math.ppas,987 :: 		
$067C	$1BA0			BTFSC	MATH___MATH_TEMPB, 7
;math.ppas,988 :: 		
$067D	$2E9A			GOTO	C3232SX1
;math.ppas,989 :: 		
$067E	$	C3232S:
;math.ppas,992 :: 		
$067E	$251C			CALL	_sdiv3232l
;math.ppas,995 :: 		
$067F	$	C3232S2:
;math.ppas,996 :: 		
$067F	$1BFC			BTFSC	STACK_12, 7
;math.ppas,997 :: 		
$0680	$2EB7			GOTO	C3232SX4
;math.ppas,998 :: 		
$0681	$	C3232SOK:
;math.ppas,999 :: 		
$0681	$1FFD			BTFSS	STACK_13, 7
;math.ppas,1000 :: 		
$0682	$2EDE			GOTO	END_ALL
;math.ppas,1001 :: 		
$0683	$09F0			COMF	STACK_0, F
;math.ppas,1002 :: 		
$0684	$09F1			COMF	STACK_1, F
;math.ppas,1003 :: 		
$0685	$09F2			COMF	STACK_2, F
;math.ppas,1004 :: 		
$0686	$09F3			COMF	STACK_3, F
;math.ppas,1005 :: 		
$0687	$0AF0			INCF	STACK_0, F
;math.ppas,1006 :: 		
$0688	$1903			BTFSC	STATUS, Z
;math.ppas,1007 :: 		
$0689	$0AF1			INCF	STACK_1, F
;math.ppas,1008 :: 		
$068A	$1903			BTFSC	STATUS, Z
;math.ppas,1009 :: 		
$068B	$0AF2			INCF	STACK_2, F
;math.ppas,1010 :: 		
$068C	$1903			BTFSC	STATUS, Z
;math.ppas,1012 :: 		
$068D	$0AF3			INCF	STACK_3, F
;math.ppas,1013 :: 		
$068E	$09F8			COMF	STACK_8, F
;math.ppas,1014 :: 		
$068F	$09F9			COMF	STACK_9, F
;math.ppas,1015 :: 		
$0690	$09FA			COMF	STACK_10, F
;math.ppas,1016 :: 		
$0691	$09FB			COMF	STACK_11, F
;math.ppas,1017 :: 		
$0692	$0AF8			INCF	STACK_8, F
;math.ppas,1018 :: 		
$0693	$1903			BTFSC	STATUS, Z
;math.ppas,1019 :: 		
$0694	$0AF9			INCF	STACK_9, F
;math.ppas,1020 :: 		
$0695	$1903			BTFSC	STATUS, Z
;math.ppas,1021 :: 		
$0696	$0AFA			INCF	STACK_10, F
;math.ppas,1022 :: 		
$0697	$1903			BTFSC	STATUS, Z
;math.ppas,1024 :: 		
$0698	$0AFB			INCF	STACK_11, F
;math.ppas,1025 :: 		
$0699	$2EDE			GOTO	END_ALL
;math.ppas,1026 :: 		
$069A	$	C3232SX1:
;math.ppas,1027 :: 		
$069A	$1FF7			BTFSS	STACK_7, 7
;math.ppas,1028 :: 		
$069B	$2EB1			GOTO	C3232SX3
;math.ppas,1029 :: 		
$069C	$1BF3			BTFSC	STACK_3, 7
;math.ppas,1030 :: 		
$069D	$2EAB			GOTO	C3232SX2
;math.ppas,1031 :: 		
$069E	$0873			MOVF	STACK_3, W
;math.ppas,1032 :: 		
$069F	$00FB			MOVWF	STACK_11
;math.ppas,1033 :: 		
$06A0	$0872			MOVF	STACK_2, W
;math.ppas,1034 :: 		
$06A1	$00FA			MOVWF	STACK_10
;math.ppas,1035 :: 		
$06A2	$0871			MOVF	STACK_1, W
;math.ppas,1036 :: 		
$06A3	$00F9			MOVWF	STACK_9
;math.ppas,1037 :: 		
$06A4	$0870			MOVF	STACK_0, W
;math.ppas,1038 :: 		
$06A5	$00F8			MOVWF	STACK_8
;math.ppas,1039 :: 		
$06A6	$01F3			CLRF	STACK_3
;math.ppas,1040 :: 		
$06A7	$01F2			CLRF	STACK_2
;math.ppas,1041 :: 		
$06A8	$01F1			CLRF	STACK_1
;math.ppas,1042 :: 		
$06A9	$01F0			CLRF	STACK_0
;math.ppas,1043 :: 		
$06AA	$2E81			GOTO	C3232SOK
;math.ppas,1044 :: 		
$06AB	$	C3232SX2:
;math.ppas,1045 :: 		
$06AB	$01F3			CLRF	STACK_3
;math.ppas,1046 :: 		
$06AC	$01F2			CLRF	STACK_2
;math.ppas,1047 :: 		
$06AD	$01F1			CLRF	STACK_1
;math.ppas,1048 :: 		
$06AE	$01F0			CLRF	STACK_0
;math.ppas,1049 :: 		
$06AF	$0AF0			INCF	STACK_0, F
;math.ppas,1051 :: 		
$06B0	$3400			RETLW	0X00
;math.ppas,1052 :: 		
$06B1	$	C3232SX3:
;math.ppas,1053 :: 		
$06B1	$09F3			COMF	STACK_3, F
;math.ppas,1054 :: 		
$06B2	$09F2			COMF	STACK_2, F
;math.ppas,1055 :: 		
$06B3	$09F1			COMF	STACK_1, F
;math.ppas,1057 :: 		
$06B4	$09F0			COMF	STACK_0, F
;math.ppas,1059 :: 		
$06B5	$17FC			BSF	STACK_12, 7
;math.ppas,1060 :: 		
$06B6	$2E7E			GOTO	C3232S
;math.ppas,1061 :: 		
$06B7	$	C3232SX4:
;math.ppas,1062 :: 		
$06B7	$0AF8			INCF	STACK_8, F
;math.ppas,1063 :: 		
$06B8	$1903			BTFSC	STATUS, Z
;math.ppas,1064 :: 		
$06B9	$0AF9			INCF	STACK_9, F
;math.ppas,1065 :: 		
$06BA	$1903			BTFSC	STATUS, Z
;math.ppas,1066 :: 		
$06BB	$0AFA			INCF	STACK_10, F
;math.ppas,1067 :: 		
$06BC	$1903			BTFSC	STATUS, Z
;math.ppas,1068 :: 		
$06BD	$0AFB			INCF	STACK_11, F
;math.ppas,1069 :: 		
$06BE	$0874			MOVF	STACK_4, W
;math.ppas,1070 :: 		
$06BF	$0278			SUBWF	STACK_8, W
;math.ppas,1071 :: 		
$06C0	$1D03			BTFSS	STATUS, Z
;math.ppas,1072 :: 		
$06C1	$2E81			GOTO	C3232SOK
;math.ppas,1073 :: 		
$06C2	$0875			MOVF	STACK_5, W
;math.ppas,1074 :: 		
$06C3	$0279			SUBWF	STACK_9, W
;math.ppas,1075 :: 		
$06C4	$1D03			BTFSS	STATUS, Z
;math.ppas,1076 :: 		
$06C5	$2E81			GOTO	C3232SOK
;math.ppas,1077 :: 		
$06C6	$0876			MOVF	STACK_6, W
;math.ppas,1078 :: 		
$06C7	$027A			SUBWF	STACK_10, W
;math.ppas,1079 :: 		
$06C8	$1D03			BTFSS	STATUS, Z
;math.ppas,1080 :: 		
$06C9	$2E81			GOTO	C3232SOK
;math.ppas,1081 :: 		
$06CA	$0877			MOVF	STACK_7, W
;math.ppas,1082 :: 		
$06CB	$027B			SUBWF	STACK_11, W
;math.ppas,1083 :: 		
$06CC	$1D03			BTFSS	STATUS, Z
;math.ppas,1084 :: 		
$06CD	$2E81			GOTO	C3232SOK
;math.ppas,1085 :: 		
$06CE	$01FB			CLRF	STACK_11
;math.ppas,1086 :: 		
$06CF	$01FA			CLRF	STACK_10
;math.ppas,1087 :: 		
$06D0	$01F9			CLRF	STACK_9
;math.ppas,1088 :: 		
$06D1	$01F8			CLRF	STACK_8
;math.ppas,1089 :: 		
$06D2	$0AF0			INCF	STACK_0, F
;math.ppas,1090 :: 		
$06D3	$1903			BTFSC	STATUS, Z
;math.ppas,1091 :: 		
$06D4	$0AF1			INCF	STACK_1, F
;math.ppas,1092 :: 		
$06D5	$1903			BTFSC	STATUS, Z
;math.ppas,1093 :: 		
$06D6	$0AF2			INCF	STACK_2, F
;math.ppas,1094 :: 		
$06D7	$1903			BTFSC	STATUS, Z
;math.ppas,1095 :: 		
$06D8	$0AF3			INCF	STACK_3, F
;math.ppas,1096 :: 		
$06D9	$1FF3			BTFSS	STACK_3, 7
;math.ppas,1097 :: 		
$06DA	$2E81			GOTO	C3232SOK
;math.ppas,1098 :: 		
$06DB	$01A0			CLRF	MATH___MATH_TEMPB
;math.ppas,1099 :: 		
$06DC	$1620			BSF	MATH___MATH_TEMPB, 4
;math.ppas,1100 :: 		
$06DD	$34FF			RETLW	0XFF
;math.ppas,1101 :: 		
$06DE	$	END_ALL:
;math.ppas,1102 :: 		
$06DE	$01A0			CLRF	MATH___MATH_TEMPB
;math.ppas,1103 :: 		
$06DF	$1C7C			BTFSS	STACK_12, 0
;math.ppas,1104 :: 		
$06E0	$2EE4			GOTO	AVOID_COMFREM
;math.ppas,1106 :: 		
$06E1	$158A			BSF	PCLATH, 3
$06E2	$2194			CALL	_comfrem
$06E3	$118A			BCF	PCLATH, 3
;math.ppas,1108 :: 		
$06E4	$	AVOID_COMFREM:
;math.ppas,1109 :: 		
$06E4	$3F00			ADDLW	0X00
;math.ppas,1110 :: 		
$06E5	$	math_L_11:
;math.ppas,1111 :: 		
$06E5	$0008			RETURN
$0004	$	_main:
;Khawad.ppas,6 :: 		begin
;Khawad.ppas,7 :: 		delim:='OK';
$0004	$304F			MOVLW	79
$0005	$1303			BCF	STATUS, RP1
$0006	$1283			BCF	STATUS, RP0
$0007	$00A1			MOVWF	_delim+0
$0008	$304B			MOVLW	75
$0009	$00A2			MOVWF	_delim+1
$000A	$01A3			CLRF	_delim+2
;Khawad.ppas,8 :: 		TRISB:=0;
$000B	$1683			BSF	STATUS, RP0
$000C	$0186			CLRF	TRISB, 1
;Khawad.ppas,9 :: 		PORTB:=0;
$000D	$1283			BCF	STATUS, RP0
$000E	$0186			CLRF	PORTB, 1
;Khawad.ppas,10 :: 		TRISD:=$FF;
$000F	$30FF			MOVLW	255
$0010	$1683			BSF	STATUS, RP0
$0011	$0088			MOVWF	TRISD
;Khawad.ppas,11 :: 		ADCON1:=$80;
$0012	$3080			MOVLW	128
$0013	$009F			MOVWF	ADCON1
;Khawad.ppas,12 :: 		USART_init(9600);
$0014	$3081			MOVLW	129
$0015	$0099			MOVWF	SPBRG
$0016	$1518			BSF	TXSTA, BRGH
$0017	$2744			CALL	_usart_init
;Khawad.ppas,13 :: 		usart_write_text('AT+CMGF=1');  // choix le text mode dans le module GSM
$0018	$3041			MOVLW	65
$0019	$00C1			MOVWF	?main_Local_Text+0
$001A	$3054			MOVLW	84
$001B	$00C2			MOVWF	?main_Local_Text+1
$001C	$302B			MOVLW	43
$001D	$00C3			MOVWF	?main_Local_Text+2
$001E	$3043			MOVLW	67
$001F	$00C4			MOVWF	?main_Local_Text+3
$0020	$304D			MOVLW	77
$0021	$00C5			MOVWF	?main_Local_Text+4
$0022	$3047			MOVLW	71
$0023	$00C6			MOVWF	?main_Local_Text+5
$0024	$3046			MOVLW	70
$0025	$00C7			MOVWF	?main_Local_Text+6
$0026	$303D			MOVLW	61
$0027	$00C8			MOVWF	?main_Local_Text+7
$0028	$3031			MOVLW	49
$0029	$00C9			MOVWF	?main_Local_Text+8
$002A	$01CA			CLRF	?main_Local_Text+9
$002B	$3041			MOVLW	?main_Local_Text
$002C	$00D6			MOVWF	FARG_Usart_Write_Text
$002D	$158A			BSF	PCLATH, 3
$002E	$2159			CALL	_usart_write_text
$002F	$118A			BCF	PCLATH, 3
;Khawad.ppas,14 :: 		usart_write(13); // Entre
$0030	$300D			MOVLW	13
$0031	$00DD			MOVWF	FARG_USART_Write
$0032	$158A			BSF	PCLATH, 3
$0033	$2182			CALL	_usart_write
$0034	$118A			BCF	PCLATH, 3
;Khawad.ppas,15 :: 		Delay_ms(1000);
$0035	$301A			MOVLW	26
$0036	$00FC			MOVWF	STACK_12
$0037	$30FF			MOVLW	255
$0038	$00FB			MOVWF	STACK_11
$0039	$30FF			MOVLW	255
$003A	$00FA			MOVWF	STACK_10
$003B	$0BFC			DECFSZ	STACK_12, F
$003C	$283E			GOTO	$+2
$003D	$2845			GOTO	$+8
$003E	$0BFB			DECFSZ	STACK_11, F
$003F	$2841			GOTO	$+2
$0040	$2844			GOTO	$+4
$0041	$0BFA			DECFSZ	STACK_10, F
$0042	$2841			GOTO	$-1
$0043	$283E			GOTO	$-5
$0044	$283B			GOTO	$-9
$0045	$307F			MOVLW	127
$0046	$00FB			MOVWF	STACK_11
$0047	$30FF			MOVLW	255
$0048	$00FA			MOVWF	STACK_10
$0049	$0BFB			DECFSZ	STACK_11, F
$004A	$284C			GOTO	$+2
$004B	$284F			GOTO	$+4
$004C	$0BFA			DECFSZ	STACK_10, F
$004D	$284C			GOTO	$-1
$004E	$2849			GOTO	$-5
$004F	$3058			MOVLW	88
$0050	$00FA			MOVWF	STACK_10
$0051	$0BFA			DECFSZ	STACK_10, F
$0052	$2851			GOTO	$-1
$0053	$0000			NOP
$0054	$0000			NOP
;Khawad.ppas,16 :: 		usart_write_text('AT+CNMI=1,2,0,0,0');
$0055	$3041			MOVLW	65
$0056	$00C1			MOVWF	?main_Local_Text+0
$0057	$3054			MOVLW	84
$0058	$00C2			MOVWF	?main_Local_Text+1
$0059	$302B			MOVLW	43
$005A	$00C3			MOVWF	?main_Local_Text+2
$005B	$3043			MOVLW	67
$005C	$00C4			MOVWF	?main_Local_Text+3
$005D	$304E			MOVLW	78
$005E	$00C5			MOVWF	?main_Local_Text+4
$005F	$304D			MOVLW	77
$0060	$00C6			MOVWF	?main_Local_Text+5
$0061	$3049			MOVLW	73
$0062	$00C7			MOVWF	?main_Local_Text+6
$0063	$303D			MOVLW	61
$0064	$00C8			MOVWF	?main_Local_Text+7
$0065	$3031			MOVLW	49
$0066	$00C9			MOVWF	?main_Local_Text+8
$0067	$302C			MOVLW	44
$0068	$00CA			MOVWF	?main_Local_Text+9
$0069	$3032			MOVLW	50
$006A	$00CB			MOVWF	?main_Local_Text+10
$006B	$302C			MOVLW	44
$006C	$00CC			MOVWF	?main_Local_Text+11
$006D	$3030			MOVLW	48
$006E	$00CD			MOVWF	?main_Local_Text+12
$006F	$302C			MOVLW	44
$0070	$00CE			MOVWF	?main_Local_Text+13
$0071	$3030			MOVLW	48
$0072	$00CF			MOVWF	?main_Local_Text+14
$0073	$302C			MOVLW	44
$0074	$00D0			MOVWF	?main_Local_Text+15
$0075	$3030			MOVLW	48
$0076	$00D1			MOVWF	?main_Local_Text+16
$0077	$01D2			CLRF	?main_Local_Text+17
$0078	$3041			MOVLW	?main_Local_Text
$0079	$00D6			MOVWF	FARG_Usart_Write_Text
$007A	$158A			BSF	PCLATH, 3
$007B	$2159			CALL	_usart_write_text
$007C	$118A			BCF	PCLATH, 3
;Khawad.ppas,17 :: 		usart_write(13);
$007D	$300D			MOVLW	13
$007E	$00DD			MOVWF	FARG_USART_Write
$007F	$158A			BSF	PCLATH, 3
$0080	$2182			CALL	_usart_write
$0081	$118A			BCF	PCLATH, 3
;Khawad.ppas,18 :: 		Delay_ms(1000);
$0082	$301A			MOVLW	26
$0083	$00FC			MOVWF	STACK_12
$0084	$30FF			MOVLW	255
$0085	$00FB			MOVWF	STACK_11
$0086	$30FF			MOVLW	255
$0087	$00FA			MOVWF	STACK_10
$0088	$0BFC			DECFSZ	STACK_12, F
$0089	$288B			GOTO	$+2
$008A	$2892			GOTO	$+8
$008B	$0BFB			DECFSZ	STACK_11, F
$008C	$288E			GOTO	$+2
$008D	$2891			GOTO	$+4
$008E	$0BFA			DECFSZ	STACK_10, F
$008F	$288E			GOTO	$-1
$0090	$288B			GOTO	$-5
$0091	$2888			GOTO	$-9
$0092	$307F			MOVLW	127
$0093	$00FB			MOVWF	STACK_11
$0094	$30FF			MOVLW	255
$0095	$00FA			MOVWF	STACK_10
$0096	$0BFB			DECFSZ	STACK_11, F
$0097	$2899			GOTO	$+2
$0098	$289C			GOTO	$+4
$0099	$0BFA			DECFSZ	STACK_10, F
$009A	$2899			GOTO	$-1
$009B	$2896			GOTO	$-5
$009C	$3058			MOVLW	88
$009D	$00FA			MOVWF	STACK_10
$009E	$0BFA			DECFSZ	STACK_10, F
$009F	$289E			GOTO	$-1
$00A0	$0000			NOP
$00A1	$0000			NOP
;Khawad.ppas,19 :: 		usart_write_text('AT+CMGS=+21623844488');
$00A2	$3041			MOVLW	65
$00A3	$00C1			MOVWF	?main_Local_Text+0
$00A4	$3054			MOVLW	84
$00A5	$00C2			MOVWF	?main_Local_Text+1
$00A6	$302B			MOVLW	43
$00A7	$00C3			MOVWF	?main_Local_Text+2
$00A8	$3043			MOVLW	67
$00A9	$00C4			MOVWF	?main_Local_Text+3
$00AA	$304D			MOVLW	77
$00AB	$00C5			MOVWF	?main_Local_Text+4
$00AC	$3047			MOVLW	71
$00AD	$00C6			MOVWF	?main_Local_Text+5
$00AE	$3053			MOVLW	83
$00AF	$00C7			MOVWF	?main_Local_Text+6
$00B0	$303D			MOVLW	61
$00B1	$00C8			MOVWF	?main_Local_Text+7
$00B2	$302B			MOVLW	43
$00B3	$00C9			MOVWF	?main_Local_Text+8
$00B4	$3032			MOVLW	50
$00B5	$00CA			MOVWF	?main_Local_Text+9
$00B6	$3031			MOVLW	49
$00B7	$00CB			MOVWF	?main_Local_Text+10
$00B8	$3036			MOVLW	54
$00B9	$00CC			MOVWF	?main_Local_Text+11
$00BA	$3032			MOVLW	50
$00BB	$00CD			MOVWF	?main_Local_Text+12
$00BC	$3033			MOVLW	51
$00BD	$00CE			MOVWF	?main_Local_Text+13
$00BE	$3038			MOVLW	56
$00BF	$00CF			MOVWF	?main_Local_Text+14
$00C0	$3034			MOVLW	52
$00C1	$00D0			MOVWF	?main_Local_Text+15
$00C2	$3034			MOVLW	52
$00C3	$00D1			MOVWF	?main_Local_Text+16
$00C4	$3034			MOVLW	52
$00C5	$00D2			MOVWF	?main_Local_Text+17
$00C6	$3038			MOVLW	56
$00C7	$00D3			MOVWF	?main_Local_Text+18
$00C8	$3038			MOVLW	56
$00C9	$00D4			MOVWF	?main_Local_Text+19
$00CA	$01D5			CLRF	?main_Local_Text+20
$00CB	$3041			MOVLW	?main_Local_Text
$00CC	$00D6			MOVWF	FARG_Usart_Write_Text
$00CD	$158A			BSF	PCLATH, 3
$00CE	$2159			CALL	_usart_write_text
$00CF	$118A			BCF	PCLATH, 3
;Khawad.ppas,20 :: 		usart_write(13);
$00D0	$300D			MOVLW	13
$00D1	$00DD			MOVWF	FARG_USART_Write
$00D2	$158A			BSF	PCLATH, 3
$00D3	$2182			CALL	_usart_write
$00D4	$118A			BCF	PCLATH, 3
;Khawad.ppas,21 :: 		delay_ms(500);
$00D5	$300D			MOVLW	13
$00D6	$00FC			MOVWF	STACK_12
$00D7	$30FF			MOVLW	255
$00D8	$00FB			MOVWF	STACK_11
$00D9	$30FF			MOVLW	255
$00DA	$00FA			MOVWF	STACK_10
$00DB	$0BFC			DECFSZ	STACK_12, F
$00DC	$28DE			GOTO	$+2
$00DD	$28E5			GOTO	$+8
$00DE	$0BFB			DECFSZ	STACK_11, F
$00DF	$28E1			GOTO	$+2
$00E0	$28E4			GOTO	$+4
$00E1	$0BFA			DECFSZ	STACK_10, F
$00E2	$28E1			GOTO	$-1
$00E3	$28DE			GOTO	$-5
$00E4	$28DB			GOTO	$-9
$00E5	$30BF			MOVLW	191
$00E6	$00FB			MOVWF	STACK_11
$00E7	$30FF			MOVLW	255
$00E8	$00FA			MOVWF	STACK_10
$00E9	$0BFB			DECFSZ	STACK_11, F
$00EA	$28EC			GOTO	$+2
$00EB	$28EF			GOTO	$+4
$00EC	$0BFA			DECFSZ	STACK_10, F
$00ED	$28EC			GOTO	$-1
$00EE	$28E9			GOTO	$-5
$00EF	$302B			MOVLW	43
$00F0	$00FA			MOVWF	STACK_10
$00F1	$0BFA			DECFSZ	STACK_10, F
$00F2	$28F1			GOTO	$-1
$00F3	$0000			NOP
$00F4	$0000			NOP
$00F5	$0000			NOP
;Khawad.ppas,22 :: 		usart_write_text(' sefo diablo  ');
$00F6	$3020			MOVLW	32
$00F7	$00C1			MOVWF	?main_Local_Text+0
$00F8	$3073			MOVLW	115
$00F9	$00C2			MOVWF	?main_Local_Text+1
$00FA	$3065			MOVLW	101
$00FB	$00C3			MOVWF	?main_Local_Text+2
$00FC	$3066			MOVLW	102
$00FD	$00C4			MOVWF	?main_Local_Text+3
$00FE	$306F			MOVLW	111
$00FF	$00C5			MOVWF	?main_Local_Text+4
$0100	$3020			MOVLW	32
$0101	$00C6			MOVWF	?main_Local_Text+5
$0102	$3064			MOVLW	100
$0103	$00C7			MOVWF	?main_Local_Text+6
$0104	$3069			MOVLW	105
$0105	$00C8			MOVWF	?main_Local_Text+7
$0106	$3061			MOVLW	97
$0107	$00C9			MOVWF	?main_Local_Text+8
$0108	$3062			MOVLW	98
$0109	$00CA			MOVWF	?main_Local_Text+9
$010A	$306C			MOVLW	108
$010B	$00CB			MOVWF	?main_Local_Text+10
$010C	$306F			MOVLW	111
$010D	$00CC			MOVWF	?main_Local_Text+11
$010E	$3020			MOVLW	32
$010F	$00CD			MOVWF	?main_Local_Text+12
$0110	$3020			MOVLW	32
$0111	$00CE			MOVWF	?main_Local_Text+13
$0112	$01CF			CLRF	?main_Local_Text+14
$0113	$3041			MOVLW	?main_Local_Text
$0114	$00D6			MOVWF	FARG_Usart_Write_Text
$0115	$158A			BSF	PCLATH, 3
$0116	$2159			CALL	_usart_write_text
$0117	$118A			BCF	PCLATH, 3
;Khawad.ppas,23 :: 		usart_write(13);
$0118	$300D			MOVLW	13
$0119	$00DD			MOVWF	FARG_USART_Write
$011A	$158A			BSF	PCLATH, 3
$011B	$2182			CALL	_usart_write
$011C	$118A			BCF	PCLATH, 3
;Khawad.ppas,24 :: 		delay_ms(500);
$011D	$300D			MOVLW	13
$011E	$00FC			MOVWF	STACK_12
$011F	$30FF			MOVLW	255
$0120	$00FB			MOVWF	STACK_11
$0121	$30FF			MOVLW	255
$0122	$00FA			MOVWF	STACK_10
$0123	$0BFC			DECFSZ	STACK_12, F
$0124	$2926			GOTO	$+2
$0125	$292D			GOTO	$+8
$0126	$0BFB			DECFSZ	STACK_11, F
$0127	$2929			GOTO	$+2
$0128	$292C			GOTO	$+4
$0129	$0BFA			DECFSZ	STACK_10, F
$012A	$2929			GOTO	$-1
$012B	$2926			GOTO	$-5
$012C	$2923			GOTO	$-9
$012D	$30BF			MOVLW	191
$012E	$00FB			MOVWF	STACK_11
$012F	$30FF			MOVLW	255
$0130	$00FA			MOVWF	STACK_10
$0131	$0BFB			DECFSZ	STACK_11, F
$0132	$2934			GOTO	$+2
$0133	$2937			GOTO	$+4
$0134	$0BFA			DECFSZ	STACK_10, F
$0135	$2934			GOTO	$-1
$0136	$2931			GOTO	$-5
$0137	$302B			MOVLW	43
$0138	$00FA			MOVWF	STACK_10
$0139	$0BFA			DECFSZ	STACK_10, F
$013A	$2939			GOTO	$-1
$013B	$0000			NOP
$013C	$0000			NOP
$013D	$0000			NOP
;Khawad.ppas,25 :: 		usart_write_text(' vs  ');
$013E	$3020			MOVLW	32
$013F	$00C1			MOVWF	?main_Local_Text+0
$0140	$3076			MOVLW	118
$0141	$00C2			MOVWF	?main_Local_Text+1
$0142	$3073			MOVLW	115
$0143	$00C3			MOVWF	?main_Local_Text+2
$0144	$3020			MOVLW	32
$0145	$00C4			MOVWF	?main_Local_Text+3
$0146	$3020			MOVLW	32
$0147	$00C5			MOVWF	?main_Local_Text+4
$0148	$01C6			CLRF	?main_Local_Text+5
$0149	$3041			MOVLW	?main_Local_Text
$014A	$00D6			MOVWF	FARG_Usart_Write_Text
$014B	$158A			BSF	PCLATH, 3
$014C	$2159			CALL	_usart_write_text
$014D	$118A			BCF	PCLATH, 3
;Khawad.ppas,26 :: 		usart_write(13);
$014E	$300D			MOVLW	13
$014F	$00DD			MOVWF	FARG_USART_Write
$0150	$158A			BSF	PCLATH, 3
$0151	$2182			CALL	_usart_write
$0152	$118A			BCF	PCLATH, 3
;Khawad.ppas,27 :: 		delay_ms(500);
$0153	$300D			MOVLW	13
$0154	$00FC			MOVWF	STACK_12
$0155	$30FF			MOVLW	255
$0156	$00FB			MOVWF	STACK_11
$0157	$30FF			MOVLW	255
$0158	$00FA			MOVWF	STACK_10
$0159	$0BFC			DECFSZ	STACK_12, F
$015A	$295C			GOTO	$+2
$015B	$2963			GOTO	$+8
$015C	$0BFB			DECFSZ	STACK_11, F
$015D	$295F			GOTO	$+2
$015E	$2962			GOTO	$+4
$015F	$0BFA			DECFSZ	STACK_10, F
$0160	$295F			GOTO	$-1
$0161	$295C			GOTO	$-5
$0162	$2959			GOTO	$-9
$0163	$30BF			MOVLW	191
$0164	$00FB			MOVWF	STACK_11
$0165	$30FF			MOVLW	255
$0166	$00FA			MOVWF	STACK_10
$0167	$0BFB			DECFSZ	STACK_11, F
$0168	$296A			GOTO	$+2
$0169	$296D			GOTO	$+4
$016A	$0BFA			DECFSZ	STACK_10, F
$016B	$296A			GOTO	$-1
$016C	$2967			GOTO	$-5
$016D	$302B			MOVLW	43
$016E	$00FA			MOVWF	STACK_10
$016F	$0BFA			DECFSZ	STACK_10, F
$0170	$296F			GOTO	$-1
$0171	$0000			NOP
$0172	$0000			NOP
$0173	$0000			NOP
;Khawad.ppas,28 :: 		usart_write_text(' El Broton  ');
$0174	$3020			MOVLW	32
$0175	$00C1			MOVWF	?main_Local_Text+0
$0176	$3045			MOVLW	69
$0177	$00C2			MOVWF	?main_Local_Text+1
$0178	$306C			MOVLW	108
$0179	$00C3			MOVWF	?main_Local_Text+2
$017A	$3020			MOVLW	32
$017B	$00C4			MOVWF	?main_Local_Text+3
$017C	$3042			MOVLW	66
$017D	$00C5			MOVWF	?main_Local_Text+4
$017E	$3072			MOVLW	114
$017F	$00C6			MOVWF	?main_Local_Text+5
$0180	$306F			MOVLW	111
$0181	$00C7			MOVWF	?main_Local_Text+6
$0182	$3074			MOVLW	116
$0183	$00C8			MOVWF	?main_Local_Text+7
$0184	$306F			MOVLW	111
$0185	$00C9			MOVWF	?main_Local_Text+8
$0186	$306E			MOVLW	110
$0187	$00CA			MOVWF	?main_Local_Text+9
$0188	$3020			MOVLW	32
$0189	$00CB			MOVWF	?main_Local_Text+10
$018A	$3020			MOVLW	32
$018B	$00CC			MOVWF	?main_Local_Text+11
$018C	$01CD			CLRF	?main_Local_Text+12
$018D	$3041			MOVLW	?main_Local_Text
$018E	$00D6			MOVWF	FARG_Usart_Write_Text
$018F	$158A			BSF	PCLATH, 3
$0190	$2159			CALL	_usart_write_text
$0191	$118A			BCF	PCLATH, 3
;Khawad.ppas,29 :: 		usart_write(13);
$0192	$300D			MOVLW	13
$0193	$00DD			MOVWF	FARG_USART_Write
$0194	$158A			BSF	PCLATH, 3
$0195	$2182			CALL	_usart_write
$0196	$118A			BCF	PCLATH, 3
;Khawad.ppas,30 :: 		usart_write(26);
$0197	$301A			MOVLW	26
$0198	$00DD			MOVWF	FARG_USART_Write
$0199	$158A			BSF	PCLATH, 3
$019A	$2182			CALL	_usart_write
$019B	$118A			BCF	PCLATH, 3
;Khawad.ppas,31 :: 		while true do
$019C	$	Khawad_L_2:
;Khawad.ppas,33 :: 		usart_write_text('AT+CMGR=?');
$019C	$3041			MOVLW	65
$019D	$00C1			MOVWF	?main_Local_Text+0
$019E	$3054			MOVLW	84
$019F	$00C2			MOVWF	?main_Local_Text+1
$01A0	$302B			MOVLW	43
$01A1	$00C3			MOVWF	?main_Local_Text+2
$01A2	$3043			MOVLW	67
$01A3	$00C4			MOVWF	?main_Local_Text+3
$01A4	$304D			MOVLW	77
$01A5	$00C5			MOVWF	?main_Local_Text+4
$01A6	$3047			MOVLW	71
$01A7	$00C6			MOVWF	?main_Local_Text+5
$01A8	$3052			MOVLW	82
$01A9	$00C7			MOVWF	?main_Local_Text+6
$01AA	$303D			MOVLW	61
$01AB	$00C8			MOVWF	?main_Local_Text+7
$01AC	$303F			MOVLW	63
$01AD	$00C9			MOVWF	?main_Local_Text+8
$01AE	$01CA			CLRF	?main_Local_Text+9
$01AF	$3041			MOVLW	?main_Local_Text
$01B0	$00D6			MOVWF	FARG_Usart_Write_Text
$01B1	$158A			BSF	PCLATH, 3
$01B2	$2159			CALL	_usart_write_text
$01B3	$118A			BCF	PCLATH, 3
;Khawad.ppas,34 :: 		usart_write(13);
$01B4	$300D			MOVLW	13
$01B5	$00DD			MOVWF	FARG_USART_Write
$01B6	$158A			BSF	PCLATH, 3
$01B7	$2182			CALL	_usart_write
$01B8	$118A			BCF	PCLATH, 3
;Khawad.ppas,35 :: 		for i:=0 to 1000 do
$01B9	$01A5			CLRF	_i
$01BA	$01A6			CLRF	_i+1
$01BB	$	Khawad_L_6:
$01BB	$3080			MOVLW	128
$01BC	$3A03			XORLW	3
$01BD	$00F0			MOVWF	STACK_0
$01BE	$3080			MOVLW	128
$01BF	$0626			XORWF	_i+1, 0
$01C0	$0270			SUBWF	STACK_0, 0
$01C1	$1D03			BTFSS	STATUS, Z
$01C2	$29C5			GOTO	L_main_0
$01C3	$0825			MOVF	_i, 0
$01C4	$3CE8			SUBLW	232
$01C5	$	L_main_0:
$01C5	$1C03			BTFSS	STATUS, C
$01C6	$2D1A			GOTO	Khawad_L_9
;Khawad.ppas,37 :: 		if usart_data_ready = 1 then
$01C7	$158A			BSF	PCLATH, 3
$01C8	$21A2			CALL	_usart_data_ready
$01C9	$118A			BCF	PCLATH, 3
$01CA	$0870			MOVF	STACK_0, 0
$01CB	$3A01			XORLW	1
$01CC	$1D03			BTFSS	STATUS, Z
$01CD	$29D5			GOTO	Khawad_L_11
$01CE	$	Khawad_L_10:
;Khawad.ppas,39 :: 		usart_read_text(data,delim);
$01CE	$3027			MOVLW	_data
$01CF	$00D6			MOVWF	FARG_Usart_Read_Text
$01D0	$3021			MOVLW	_delim
$01D1	$00D7			MOVWF	FARG_Usart_Read_Text+1
$01D2	$158A			BSF	PCLATH, 3
$01D3	$2000			CALL	_usart_read_text
$01D4	$118A			BCF	PCLATH, 3
;Khawad.ppas,40 :: 		end;
$01D5	$	Khawad_L_11:
$01D5	$	Khawad_L_12:
;Khawad.ppas,41 :: 		if (Strcmp(data,'S0=1') = 0) then portb.0:=1;
$01D5	$3027			MOVLW	_data
$01D6	$00D6			MOVWF	FARG_strcmp
$01D7	$3053			MOVLW	83
$01D8	$00C1			MOVWF	?main_Local_Text+0
$01D9	$3030			MOVLW	48
$01DA	$00C2			MOVWF	?main_Local_Text+1
$01DB	$303D			MOVLW	61
$01DC	$00C3			MOVWF	?main_Local_Text+2
$01DD	$3031			MOVLW	49
$01DE	$00C4			MOVWF	?main_Local_Text+3
$01DF	$01C5			CLRF	?main_Local_Text+4
$01E0	$3041			MOVLW	?main_Local_Text
$01E1	$00D7			MOVWF	FARG_strcmp+1
$01E2	$158A			BSF	PCLATH, 3
$01E3	$2043			CALL	_strcmp
$01E4	$118A			BCF	PCLATH, 3
$01E5	$3000			MOVLW	0
$01E6	$0671			XORWF	STACK_0+1, 0
$01E7	$1D03			BTFSS	STATUS, Z
$01E8	$29EB			GOTO	L_main_1
$01E9	$3000			MOVLW	0
$01EA	$0670			XORWF	STACK_0, 0
$01EB	$	L_main_1:
$01EB	$1D03			BTFSS	STATUS, Z
$01EC	$29EE			GOTO	Khawad_L_14
$01ED	$	Khawad_L_13:
$01ED	$	Khawad_L_16:
$01ED	$1406			BSF	PORTB, 0
$01EE	$	Khawad_L_17:
$01EE	$	Khawad_L_14:
$01EE	$	Khawad_L_15:
;Khawad.ppas,42 :: 		if (Strcmp(data,'S1=1') = 0) then portb.1:=1;
$01EE	$3027			MOVLW	_data
$01EF	$00D6			MOVWF	FARG_strcmp
$01F0	$3053			MOVLW	83
$01F1	$00C1			MOVWF	?main_Local_Text+0
$01F2	$3031			MOVLW	49
$01F3	$00C2			MOVWF	?main_Local_Text+1
$01F4	$303D			MOVLW	61
$01F5	$00C3			MOVWF	?main_Local_Text+2
$01F6	$3031			MOVLW	49
$01F7	$00C4			MOVWF	?main_Local_Text+3
$01F8	$01C5			CLRF	?main_Local_Text+4
$01F9	$3041			MOVLW	?main_Local_Text
$01FA	$00D7			MOVWF	FARG_strcmp+1
$01FB	$158A			BSF	PCLATH, 3
$01FC	$2043			CALL	_strcmp
$01FD	$118A			BCF	PCLATH, 3
$01FE	$3000			MOVLW	0
$01FF	$0671			XORWF	STACK_0+1, 0
$0200	$1D03			BTFSS	STATUS, Z
$0201	$2A04			GOTO	L_main_2
$0202	$3000			MOVLW	0
$0203	$0670			XORWF	STACK_0, 0
$0204	$	L_main_2:
$0204	$1D03			BTFSS	STATUS, Z
$0205	$2A07			GOTO	Khawad_L_19
$0206	$	Khawad_L_18:
$0206	$	Khawad_L_21:
$0206	$1486			BSF	PORTB, 1
$0207	$	Khawad_L_22:
$0207	$	Khawad_L_19:
$0207	$	Khawad_L_20:
;Khawad.ppas,43 :: 		if (Strcmp(data,'S2=1') = 0) then portb.2:=1;
$0207	$3027			MOVLW	_data
$0208	$00D6			MOVWF	FARG_strcmp
$0209	$3053			MOVLW	83
$020A	$00C1			MOVWF	?main_Local_Text+0
$020B	$3032			MOVLW	50
$020C	$00C2			MOVWF	?main_Local_Text+1
$020D	$303D			MOVLW	61
$020E	$00C3			MOVWF	?main_Local_Text+2
$020F	$3031			MOVLW	49
$0210	$00C4			MOVWF	?main_Local_Text+3
$0211	$01C5			CLRF	?main_Local_Text+4
$0212	$3041			MOVLW	?main_Local_Text
$0213	$00D7			MOVWF	FARG_strcmp+1
$0214	$158A			BSF	PCLATH, 3
$0215	$2043			CALL	_strcmp
$0216	$118A			BCF	PCLATH, 3
$0217	$3000			MOVLW	0
$0218	$0671			XORWF	STACK_0+1, 0
$0219	$1D03			BTFSS	STATUS, Z
$021A	$2A1D			GOTO	L_main_3
$021B	$3000			MOVLW	0
$021C	$0670			XORWF	STACK_0, 0
$021D	$	L_main_3:
$021D	$1D03			BTFSS	STATUS, Z
$021E	$2A20			GOTO	Khawad_L_24
$021F	$	Khawad_L_23:
$021F	$	Khawad_L_26:
$021F	$1506			BSF	PORTB, 2
$0220	$	Khawad_L_27:
$0220	$	Khawad_L_24:
$0220	$	Khawad_L_25:
;Khawad.ppas,44 :: 		if (Strcmp(data,'S3=1') = 0) then portb.3:=1;
$0220	$3027			MOVLW	_data
$0221	$00D6			MOVWF	FARG_strcmp
$0222	$3053			MOVLW	83
$0223	$00C1			MOVWF	?main_Local_Text+0
$0224	$3033			MOVLW	51
$0225	$00C2			MOVWF	?main_Local_Text+1
$0226	$303D			MOVLW	61
$0227	$00C3			MOVWF	?main_Local_Text+2
$0228	$3031			MOVLW	49
$0229	$00C4			MOVWF	?main_Local_Text+3
$022A	$01C5			CLRF	?main_Local_Text+4
$022B	$3041			MOVLW	?main_Local_Text
$022C	$00D7			MOVWF	FARG_strcmp+1
$022D	$158A			BSF	PCLATH, 3
$022E	$2043			CALL	_strcmp
$022F	$118A			BCF	PCLATH, 3
$0230	$3000			MOVLW	0
$0231	$0671			XORWF	STACK_0+1, 0
$0232	$1D03			BTFSS	STATUS, Z
$0233	$2A36			GOTO	L_main_4
$0234	$3000			MOVLW	0
$0235	$0670			XORWF	STACK_0, 0
$0236	$	L_main_4:
$0236	$1D03			BTFSS	STATUS, Z
$0237	$2A39			GOTO	Khawad_L_29
$0238	$	Khawad_L_28:
$0238	$	Khawad_L_31:
$0238	$1586			BSF	PORTB, 3
$0239	$	Khawad_L_32:
$0239	$	Khawad_L_29:
$0239	$	Khawad_L_30:
;Khawad.ppas,46 :: 		if (Strcmp(data,'S0=0') = 0) then portb.0:=0;
$0239	$3027			MOVLW	_data
$023A	$00D6			MOVWF	FARG_strcmp
$023B	$3053			MOVLW	83
$023C	$00C1			MOVWF	?main_Local_Text+0
$023D	$3030			MOVLW	48
$023E	$00C2			MOVWF	?main_Local_Text+1
$023F	$303D			MOVLW	61
$0240	$00C3			MOVWF	?main_Local_Text+2
$0241	$3030			MOVLW	48
$0242	$00C4			MOVWF	?main_Local_Text+3
$0243	$01C5			CLRF	?main_Local_Text+4
$0244	$3041			MOVLW	?main_Local_Text
$0245	$00D7			MOVWF	FARG_strcmp+1
$0246	$158A			BSF	PCLATH, 3
$0247	$2043			CALL	_strcmp
$0248	$118A			BCF	PCLATH, 3
$0249	$3000			MOVLW	0
$024A	$0671			XORWF	STACK_0+1, 0
$024B	$1D03			BTFSS	STATUS, Z
$024C	$2A4F			GOTO	L_main_5
$024D	$3000			MOVLW	0
$024E	$0670			XORWF	STACK_0, 0
$024F	$	L_main_5:
$024F	$1D03			BTFSS	STATUS, Z
$0250	$2A52			GOTO	Khawad_L_34
$0251	$	Khawad_L_33:
$0251	$1006			BCF	PORTB, 0
$0252	$	Khawad_L_37:
$0252	$	Khawad_L_34:
$0252	$	Khawad_L_35:
;Khawad.ppas,47 :: 		if (Strcmp(data,'S1=0') = 0) then portb.1:=0;
$0252	$3027			MOVLW	_data
$0253	$00D6			MOVWF	FARG_strcmp
$0254	$3053			MOVLW	83
$0255	$00C1			MOVWF	?main_Local_Text+0
$0256	$3031			MOVLW	49
$0257	$00C2			MOVWF	?main_Local_Text+1
$0258	$303D			MOVLW	61
$0259	$00C3			MOVWF	?main_Local_Text+2
$025A	$3030			MOVLW	48
$025B	$00C4			MOVWF	?main_Local_Text+3
$025C	$01C5			CLRF	?main_Local_Text+4
$025D	$3041			MOVLW	?main_Local_Text
$025E	$00D7			MOVWF	FARG_strcmp+1
$025F	$158A			BSF	PCLATH, 3
$0260	$2043			CALL	_strcmp
$0261	$118A			BCF	PCLATH, 3
$0262	$3000			MOVLW	0
$0263	$0671			XORWF	STACK_0+1, 0
$0264	$1D03			BTFSS	STATUS, Z
$0265	$2A68			GOTO	L_main_6
$0266	$3000			MOVLW	0
$0267	$0670			XORWF	STACK_0, 0
$0268	$	L_main_6:
$0268	$1D03			BTFSS	STATUS, Z
$0269	$2A6B			GOTO	Khawad_L_39
$026A	$	Khawad_L_38:
$026A	$1086			BCF	PORTB, 1
$026B	$	Khawad_L_42:
$026B	$	Khawad_L_39:
$026B	$	Khawad_L_40:
;Khawad.ppas,48 :: 		if (Strcmp(data,'S2=0') = 0) then portb.2:=0;
$026B	$3027			MOVLW	_data
$026C	$00D6			MOVWF	FARG_strcmp
$026D	$3053			MOVLW	83
$026E	$00C1			MOVWF	?main_Local_Text+0
$026F	$3032			MOVLW	50
$0270	$00C2			MOVWF	?main_Local_Text+1
$0271	$303D			MOVLW	61
$0272	$00C3			MOVWF	?main_Local_Text+2
$0273	$3030			MOVLW	48
$0274	$00C4			MOVWF	?main_Local_Text+3
$0275	$01C5			CLRF	?main_Local_Text+4
$0276	$3041			MOVLW	?main_Local_Text
$0277	$00D7			MOVWF	FARG_strcmp+1
$0278	$158A			BSF	PCLATH, 3
$0279	$2043			CALL	_strcmp
$027A	$118A			BCF	PCLATH, 3
$027B	$3000			MOVLW	0
$027C	$0671			XORWF	STACK_0+1, 0
$027D	$1D03			BTFSS	STATUS, Z
$027E	$2A81			GOTO	L_main_7
$027F	$3000			MOVLW	0
$0280	$0670			XORWF	STACK_0, 0
$0281	$	L_main_7:
$0281	$1D03			BTFSS	STATUS, Z
$0282	$2A84			GOTO	Khawad_L_44
$0283	$	Khawad_L_43:
$0283	$1106			BCF	PORTB, 2
$0284	$	Khawad_L_47:
$0284	$	Khawad_L_44:
$0284	$	Khawad_L_45:
;Khawad.ppas,49 :: 		if (Strcmp(data,'S3=0') = 0) then portb.3:=0;
$0284	$3027			MOVLW	_data
$0285	$00D6			MOVWF	FARG_strcmp
$0286	$3053			MOVLW	83
$0287	$00C1			MOVWF	?main_Local_Text+0
$0288	$3033			MOVLW	51
$0289	$00C2			MOVWF	?main_Local_Text+1
$028A	$303D			MOVLW	61
$028B	$00C3			MOVWF	?main_Local_Text+2
$028C	$3030			MOVLW	48
$028D	$00C4			MOVWF	?main_Local_Text+3
$028E	$01C5			CLRF	?main_Local_Text+4
$028F	$3041			MOVLW	?main_Local_Text
$0290	$00D7			MOVWF	FARG_strcmp+1
$0291	$158A			BSF	PCLATH, 3
$0292	$2043			CALL	_strcmp
$0293	$118A			BCF	PCLATH, 3
$0294	$3000			MOVLW	0
$0295	$0671			XORWF	STACK_0+1, 0
$0296	$1D03			BTFSS	STATUS, Z
$0297	$2A9A			GOTO	L_main_8
$0298	$3000			MOVLW	0
$0299	$0670			XORWF	STACK_0, 0
$029A	$	L_main_8:
$029A	$1D03			BTFSS	STATUS, Z
$029B	$2A9D			GOTO	Khawad_L_49
$029C	$	Khawad_L_48:
$029C	$1186			BCF	PORTB, 3
$029D	$	Khawad_L_52:
$029D	$	Khawad_L_49:
$029D	$	Khawad_L_50:
;Khawad.ppas,52 :: 		if (Strcmp(data,'ENTREE') = 0) then
$029D	$3027			MOVLW	_data
$029E	$00D6			MOVWF	FARG_strcmp
$029F	$3045			MOVLW	69
$02A0	$00C1			MOVWF	?main_Local_Text+0
$02A1	$304E			MOVLW	78
$02A2	$00C2			MOVWF	?main_Local_Text+1
$02A3	$3054			MOVLW	84
$02A4	$00C3			MOVWF	?main_Local_Text+2
$02A5	$3052			MOVLW	82
$02A6	$00C4			MOVWF	?main_Local_Text+3
$02A7	$3045			MOVLW	69
$02A8	$00C5			MOVWF	?main_Local_Text+4
$02A9	$3045			MOVLW	69
$02AA	$00C6			MOVWF	?main_Local_Text+5
$02AB	$01C7			CLRF	?main_Local_Text+6
$02AC	$3041			MOVLW	?main_Local_Text
$02AD	$00D7			MOVWF	FARG_strcmp+1
$02AE	$158A			BSF	PCLATH, 3
$02AF	$2043			CALL	_strcmp
$02B0	$118A			BCF	PCLATH, 3
$02B1	$3000			MOVLW	0
$02B2	$0671			XORWF	STACK_0+1, 0
$02B3	$1D03			BTFSS	STATUS, Z
$02B4	$2AB7			GOTO	L_main_9
$02B5	$3000			MOVLW	0
$02B6	$0670			XORWF	STACK_0, 0
$02B7	$	L_main_9:
$02B7	$1D03			BTFSS	STATUS, Z
$02B8	$2B1E			GOTO	Khawad_L_54
$02B9	$	Khawad_L_53:
;Khawad.ppas,54 :: 		usart_write_text(' E0 E1 E2 E3 ');
$02B9	$3020			MOVLW	32
$02BA	$00C1			MOVWF	?main_Local_Text+0
$02BB	$3045			MOVLW	69
$02BC	$00C2			MOVWF	?main_Local_Text+1
$02BD	$3030			MOVLW	48
$02BE	$00C3			MOVWF	?main_Local_Text+2
$02BF	$3020			MOVLW	32
$02C0	$00C4			MOVWF	?main_Local_Text+3
$02C1	$3045			MOVLW	69
$02C2	$00C5			MOVWF	?main_Local_Text+4
$02C3	$3031			MOVLW	49
$02C4	$00C6			MOVWF	?main_Local_Text+5
$02C5	$3020			MOVLW	32
$02C6	$00C7			MOVWF	?main_Local_Text+6
$02C7	$3045			MOVLW	69
$02C8	$00C8			MOVWF	?main_Local_Text+7
$02C9	$3032			MOVLW	50
$02CA	$00C9			MOVWF	?main_Local_Text+8
$02CB	$3020			MOVLW	32
$02CC	$00CA			MOVWF	?main_Local_Text+9
$02CD	$3045			MOVLW	69
$02CE	$00CB			MOVWF	?main_Local_Text+10
$02CF	$3033			MOVLW	51
$02D0	$00CC			MOVWF	?main_Local_Text+11
$02D1	$3020			MOVLW	32
$02D2	$00CD			MOVWF	?main_Local_Text+12
$02D3	$01CE			CLRF	?main_Local_Text+13
$02D4	$3041			MOVLW	?main_Local_Text
$02D5	$00D6			MOVWF	FARG_Usart_Write_Text
$02D6	$158A			BSF	PCLATH, 3
$02D7	$2159			CALL	_usart_write_text
$02D8	$118A			BCF	PCLATH, 3
;Khawad.ppas,55 :: 		usart_write(13);
$02D9	$300D			MOVLW	13
$02DA	$00DD			MOVWF	FARG_USART_Write
$02DB	$158A			BSF	PCLATH, 3
$02DC	$2182			CALL	_usart_write
$02DD	$118A			BCF	PCLATH, 3
;Khawad.ppas,56 :: 		for j:= 0 to 3 do
$02DE	$01BB			CLRF	_j
$02DF	$01BC			CLRF	_j+1
$02E0	$	Khawad_L_56:
$02E0	$3080			MOVLW	128
$02E1	$00F0			MOVWF	STACK_0
$02E2	$3080			MOVLW	128
$02E3	$063C			XORWF	_j+1, 0
$02E4	$0270			SUBWF	STACK_0, 0
$02E5	$1D03			BTFSS	STATUS, Z
$02E6	$2AE9			GOTO	L_main_10
$02E7	$083B			MOVF	_j, 0
$02E8	$3C03			SUBLW	3
$02E9	$	L_main_10:
$02E9	$1C03			BTFSS	STATUS, C
$02EA	$2B19			GOTO	Khawad_L_59
;Khawad.ppas,58 :: 		usart_write_text('  ');
$02EB	$3020			MOVLW	32
$02EC	$00C1			MOVWF	?main_Local_Text+0
$02ED	$3020			MOVLW	32
$02EE	$00C2			MOVWF	?main_Local_Text+1
$02EF	$01C3			CLRF	?main_Local_Text+2
$02F0	$3041			MOVLW	?main_Local_Text
$02F1	$00D6			MOVWF	FARG_Usart_Write_Text
$02F2	$158A			BSF	PCLATH, 3
$02F3	$2159			CALL	_usart_write_text
$02F4	$118A			BCF	PCLATH, 3
;Khawad.ppas,59 :: 		usart_write(portd.j+ 48);
$02F5	$3001			MOVLW	1
$02F6	$00F0			MOVWF	STACK_0
$02F7	$083B			MOVF	_j, 0
$02F8	$	L_main_11:
$02F8	$1903			BTFSC	STATUS, Z
$02F9	$2AFE			GOTO	L_main_12
$02FA	$0DF0			RLF	STACK_0, 1
$02FB	$1070			BCF	STACK_0, 0
$02FC	$3FFF			ADDLW	255
$02FD	$2AF8			GOTO	L_main_11
$02FE	$	L_main_12:
$02FE	$0808			MOVF	PORTD, 0
$02FF	$05F0			ANDWF	STACK_0, 1
$0300	$083B			MOVF	_j, 0
$0301	$	L_main_13:
$0301	$1903			BTFSC	STATUS, Z
$0302	$2B07			GOTO	L_main_14
$0303	$0CF0			RRF	STACK_0, 1
$0304	$13F0			BCF	STACK_0, 7
$0305	$3FFF			ADDLW	255
$0306	$2B01			GOTO	L_main_13
$0307	$	L_main_14:
$0307	$3030			MOVLW	48
$0308	$0770			ADDWF	STACK_0, 0
$0309	$00DD			MOVWF	FARG_USART_Write
$030A	$158A			BSF	PCLATH, 3
$030B	$2182			CALL	_usart_write
$030C	$118A			BCF	PCLATH, 3
;Khawad.ppas,60 :: 		end;
$030D	$3000			MOVLW	0
$030E	$063C			XORWF	_j+1, 0
$030F	$1D03			BTFSS	STATUS, Z
$0310	$2B13			GOTO	L_main_15
$0311	$3003			MOVLW	3
$0312	$063B			XORWF	_j, 0
$0313	$	L_main_15:
$0313	$1903			BTFSC	STATUS, Z
$0314	$2B19			GOTO	Khawad_L_59
$0315	$	Khawad_L_57:
$0315	$0ABB			INCF	_j, 1
$0316	$1903			BTFSC	STATUS, Z
$0317	$0ABC			INCF	_j+1, 1
$0318	$2AE0			GOTO	Khawad_L_56
$0319	$	Khawad_L_59:
;Khawad.ppas,61 :: 		usart_write(13);
$0319	$300D			MOVLW	13
$031A	$00DD			MOVWF	FARG_USART_Write
$031B	$158A			BSF	PCLATH, 3
$031C	$2182			CALL	_usart_write
$031D	$118A			BCF	PCLATH, 3
;Khawad.ppas,62 :: 		end;
$031E	$	Khawad_L_54:
$031E	$	Khawad_L_55:
;Khawad.ppas,66 :: 		if (Strcmp(data,'ANAL0') = 0) then
$031E	$3027			MOVLW	_data
$031F	$00D6			MOVWF	FARG_strcmp
$0320	$3041			MOVLW	65
$0321	$00C1			MOVWF	?main_Local_Text+0
$0322	$304E			MOVLW	78
$0323	$00C2			MOVWF	?main_Local_Text+1
$0324	$3041			MOVLW	65
$0325	$00C3			MOVWF	?main_Local_Text+2
$0326	$304C			MOVLW	76
$0327	$00C4			MOVWF	?main_Local_Text+3
$0328	$3030			MOVLW	48
$0329	$00C5			MOVWF	?main_Local_Text+4
$032A	$01C6			CLRF	?main_Local_Text+5
$032B	$3041			MOVLW	?main_Local_Text
$032C	$00D7			MOVWF	FARG_strcmp+1
$032D	$158A			BSF	PCLATH, 3
$032E	$2043			CALL	_strcmp
$032F	$118A			BCF	PCLATH, 3
$0330	$3000			MOVLW	0
$0331	$0671			XORWF	STACK_0+1, 0
$0332	$1D03			BTFSS	STATUS, Z
$0333	$2B36			GOTO	L_main_16
$0334	$3000			MOVLW	0
$0335	$0670			XORWF	STACK_0, 0
$0336	$	L_main_16:
$0336	$1D03			BTFSS	STATUS, Z
$0337	$2B95			GOTO	Khawad_L_61
$0338	$	Khawad_L_60:
;Khawad.ppas,68 :: 		H:= adc_read(0);
$0338	$01D6			CLRF	FARG_ADC_read, 1
$0339	$158A			BSF	PCLATH, 3
$033A	$2089			CALL	_adc_read
$033B	$118A			BCF	PCLATH, 3
$033C	$0870			MOVF	STACK_0, 0
$033D	$00BD			MOVWF	_h
$033E	$0871			MOVF	STACK_0+1, 0
$033F	$00BE			MOVWF	_h+1
$0340	$01BF			CLRF	_h+2
$0341	$01C0			CLRF	_h+3
;Khawad.ppas,69 :: 		H:=(h*5000)/1024 ;
$0342	$083D			MOVF	_h, 0
$0343	$00F0			MOVWF	STACK_0
$0344	$083E			MOVF	_h+1, 0
$0345	$00F1			MOVWF	STACK_0+1
$0346	$083F			MOVF	_h+2, 0
$0347	$00F2			MOVWF	STACK_0+2
$0348	$0840			MOVF	_h+3, 0
$0349	$00F3			MOVWF	STACK_0+3
$034A	$3088			MOVLW	136
$034B	$00F4			MOVWF	STACK_4
$034C	$3013			MOVLW	19
$034D	$00F5			MOVWF	STACK_4+1
$034E	$01F6			CLRF	STACK_4+2
$034F	$01F7			CLRF	STACK_4+3
$0350	$158A			BSF	PCLATH, 3
$0351	$20CA			CALL	_mul_32x32_s
$0352	$118A			BCF	PCLATH, 3
$0353	$3000			MOVLW	0
$0354	$00F4			MOVWF	STACK_4
$0355	$3004			MOVLW	4
$0356	$00F5			MOVWF	STACK_4+1
$0357	$01F6			CLRF	STACK_4+2
$0358	$01F7			CLRF	STACK_4+3
$0359	$264A			CALL	_div_32x32_s
$035A	$0870			MOVF	STACK_0, 0
$035B	$00BD			MOVWF	_h
$035C	$0871			MOVF	STACK_0+1, 0
$035D	$00BE			MOVWF	_h+1
$035E	$0872			MOVF	STACK_0+2, 0
$035F	$00BF			MOVWF	_h+2
$0360	$0873			MOVF	STACK_0+3, 0
$0361	$00C0			MOVWF	_h+3
;Khawad.ppas,70 :: 		wordtostr(h,data) ;
$0362	$0870			MOVF	STACK_0, 0
$0363	$00D6			MOVWF	FARG_WordToStr
$0364	$0871			MOVF	STACK_0+1, 0
$0365	$00D7			MOVWF	FARG_WordToStr+1
$0366	$3027			MOVLW	_data
$0367	$00D8			MOVWF	FARG_WordToStr+2
$0368	$26E6			CALL	_wordtostr
;Khawad.ppas,71 :: 		usart_write_text('ANAL 0 = ');
$0369	$3041			MOVLW	65
$036A	$00C1			MOVWF	?main_Local_Text+0
$036B	$304E			MOVLW	78
$036C	$00C2			MOVWF	?main_Local_Text+1
$036D	$3041			MOVLW	65
$036E	$00C3			MOVWF	?main_Local_Text+2
$036F	$304C			MOVLW	76
$0370	$00C4			MOVWF	?main_Local_Text+3
$0371	$3020			MOVLW	32
$0372	$00C5			MOVWF	?main_Local_Text+4
$0373	$3030			MOVLW	48
$0374	$00C6			MOVWF	?main_Local_Text+5
$0375	$3020			MOVLW	32
$0376	$00C7			MOVWF	?main_Local_Text+6
$0377	$303D			MOVLW	61
$0378	$00C8			MOVWF	?main_Local_Text+7
$0379	$3020			MOVLW	32
$037A	$00C9			MOVWF	?main_Local_Text+8
$037B	$01CA			CLRF	?main_Local_Text+9
$037C	$3041			MOVLW	?main_Local_Text
$037D	$00D6			MOVWF	FARG_Usart_Write_Text
$037E	$158A			BSF	PCLATH, 3
$037F	$2159			CALL	_usart_write_text
$0380	$118A			BCF	PCLATH, 3
;Khawad.ppas,72 :: 		usart_write_text(data);
$0381	$3027			MOVLW	_data
$0382	$00D6			MOVWF	FARG_Usart_Write_Text
$0383	$158A			BSF	PCLATH, 3
$0384	$2159			CALL	_usart_write_text
$0385	$118A			BCF	PCLATH, 3
;Khawad.ppas,73 :: 		usart_write_text('mV');
$0386	$306D			MOVLW	109
$0387	$00C1			MOVWF	?main_Local_Text+0
$0388	$3056			MOVLW	86
$0389	$00C2			MOVWF	?main_Local_Text+1
$038A	$01C3			CLRF	?main_Local_Text+2
$038B	$3041			MOVLW	?main_Local_Text
$038C	$00D6			MOVWF	FARG_Usart_Write_Text
$038D	$158A			BSF	PCLATH, 3
$038E	$2159			CALL	_usart_write_text
$038F	$118A			BCF	PCLATH, 3
;Khawad.ppas,74 :: 		usart_write(13);
$0390	$300D			MOVLW	13
$0391	$00DD			MOVWF	FARG_USART_Write
$0392	$158A			BSF	PCLATH, 3
$0393	$2182			CALL	_usart_write
$0394	$118A			BCF	PCLATH, 3
;Khawad.ppas,75 :: 		end;
$0395	$	Khawad_L_61:
$0395	$	Khawad_L_62:
;Khawad.ppas,76 :: 		if (Strcmp(data,'ANAL1') = 0) then
$0395	$3027			MOVLW	_data
$0396	$00D6			MOVWF	FARG_strcmp
$0397	$3041			MOVLW	65
$0398	$00C1			MOVWF	?main_Local_Text+0
$0399	$304E			MOVLW	78
$039A	$00C2			MOVWF	?main_Local_Text+1
$039B	$3041			MOVLW	65
$039C	$00C3			MOVWF	?main_Local_Text+2
$039D	$304C			MOVLW	76
$039E	$00C4			MOVWF	?main_Local_Text+3
$039F	$3031			MOVLW	49
$03A0	$00C5			MOVWF	?main_Local_Text+4
$03A1	$01C6			CLRF	?main_Local_Text+5
$03A2	$3041			MOVLW	?main_Local_Text
$03A3	$00D7			MOVWF	FARG_strcmp+1
$03A4	$158A			BSF	PCLATH, 3
$03A5	$2043			CALL	_strcmp
$03A6	$118A			BCF	PCLATH, 3
$03A7	$3000			MOVLW	0
$03A8	$0671			XORWF	STACK_0+1, 0
$03A9	$1D03			BTFSS	STATUS, Z
$03AA	$2BAD			GOTO	L_main_17
$03AB	$3000			MOVLW	0
$03AC	$0670			XORWF	STACK_0, 0
$03AD	$	L_main_17:
$03AD	$1D03			BTFSS	STATUS, Z
$03AE	$2C0D			GOTO	Khawad_L_64
$03AF	$	Khawad_L_63:
;Khawad.ppas,78 :: 		H:= adc_read(1);
$03AF	$3001			MOVLW	1
$03B0	$00D6			MOVWF	FARG_ADC_read
$03B1	$158A			BSF	PCLATH, 3
$03B2	$2089			CALL	_adc_read
$03B3	$118A			BCF	PCLATH, 3
$03B4	$0870			MOVF	STACK_0, 0
$03B5	$00BD			MOVWF	_h
$03B6	$0871			MOVF	STACK_0+1, 0
$03B7	$00BE			MOVWF	_h+1
$03B8	$01BF			CLRF	_h+2
$03B9	$01C0			CLRF	_h+3
;Khawad.ppas,79 :: 		H:=(h*5000)/1024 ;
$03BA	$083D			MOVF	_h, 0
$03BB	$00F0			MOVWF	STACK_0
$03BC	$083E			MOVF	_h+1, 0
$03BD	$00F1			MOVWF	STACK_0+1
$03BE	$083F			MOVF	_h+2, 0
$03BF	$00F2			MOVWF	STACK_0+2
$03C0	$0840			MOVF	_h+3, 0
$03C1	$00F3			MOVWF	STACK_0+3
$03C2	$3088			MOVLW	136
$03C3	$00F4			MOVWF	STACK_4
$03C4	$3013			MOVLW	19
$03C5	$00F5			MOVWF	STACK_4+1
$03C6	$01F6			CLRF	STACK_4+2
$03C7	$01F7			CLRF	STACK_4+3
$03C8	$158A			BSF	PCLATH, 3
$03C9	$20CA			CALL	_mul_32x32_s
$03CA	$118A			BCF	PCLATH, 3
$03CB	$3000			MOVLW	0
$03CC	$00F4			MOVWF	STACK_4
$03CD	$3004			MOVLW	4
$03CE	$00F5			MOVWF	STACK_4+1
$03CF	$01F6			CLRF	STACK_4+2
$03D0	$01F7			CLRF	STACK_4+3
$03D1	$264A			CALL	_div_32x32_s
$03D2	$0870			MOVF	STACK_0, 0
$03D3	$00BD			MOVWF	_h
$03D4	$0871			MOVF	STACK_0+1, 0
$03D5	$00BE			MOVWF	_h+1
$03D6	$0872			MOVF	STACK_0+2, 0
$03D7	$00BF			MOVWF	_h+2
$03D8	$0873			MOVF	STACK_0+3, 0
$03D9	$00C0			MOVWF	_h+3
;Khawad.ppas,80 :: 		wordtostr(h,data) ;
$03DA	$0870			MOVF	STACK_0, 0
$03DB	$00D6			MOVWF	FARG_WordToStr
$03DC	$0871			MOVF	STACK_0+1, 0
$03DD	$00D7			MOVWF	FARG_WordToStr+1
$03DE	$3027			MOVLW	_data
$03DF	$00D8			MOVWF	FARG_WordToStr+2
$03E0	$26E6			CALL	_wordtostr
;Khawad.ppas,81 :: 		usart_write_text('ANAL 1 = ');
$03E1	$3041			MOVLW	65
$03E2	$00C1			MOVWF	?main_Local_Text+0
$03E3	$304E			MOVLW	78
$03E4	$00C2			MOVWF	?main_Local_Text+1
$03E5	$3041			MOVLW	65
$03E6	$00C3			MOVWF	?main_Local_Text+2
$03E7	$304C			MOVLW	76
$03E8	$00C4			MOVWF	?main_Local_Text+3
$03E9	$3020			MOVLW	32
$03EA	$00C5			MOVWF	?main_Local_Text+4
$03EB	$3031			MOVLW	49
$03EC	$00C6			MOVWF	?main_Local_Text+5
$03ED	$3020			MOVLW	32
$03EE	$00C7			MOVWF	?main_Local_Text+6
$03EF	$303D			MOVLW	61
$03F0	$00C8			MOVWF	?main_Local_Text+7
$03F1	$3020			MOVLW	32
$03F2	$00C9			MOVWF	?main_Local_Text+8
$03F3	$01CA			CLRF	?main_Local_Text+9
$03F4	$3041			MOVLW	?main_Local_Text
$03F5	$00D6			MOVWF	FARG_Usart_Write_Text
$03F6	$158A			BSF	PCLATH, 3
$03F7	$2159			CALL	_usart_write_text
$03F8	$118A			BCF	PCLATH, 3
;Khawad.ppas,82 :: 		usart_write_text(data);
$03F9	$3027			MOVLW	_data
$03FA	$00D6			MOVWF	FARG_Usart_Write_Text
$03FB	$158A			BSF	PCLATH, 3
$03FC	$2159			CALL	_usart_write_text
$03FD	$118A			BCF	PCLATH, 3
;Khawad.ppas,83 :: 		usart_write_text('mV');
$03FE	$306D			MOVLW	109
$03FF	$00C1			MOVWF	?main_Local_Text+0
$0400	$3056			MOVLW	86
$0401	$00C2			MOVWF	?main_Local_Text+1
$0402	$01C3			CLRF	?main_Local_Text+2
$0403	$3041			MOVLW	?main_Local_Text
$0404	$00D6			MOVWF	FARG_Usart_Write_Text
$0405	$158A			BSF	PCLATH, 3
$0406	$2159			CALL	_usart_write_text
$0407	$118A			BCF	PCLATH, 3
;Khawad.ppas,84 :: 		usart_write(13);
$0408	$300D			MOVLW	13
$0409	$00DD			MOVWF	FARG_USART_Write
$040A	$158A			BSF	PCLATH, 3
$040B	$2182			CALL	_usart_write
$040C	$118A			BCF	PCLATH, 3
;Khawad.ppas,85 :: 		end;
$040D	$	Khawad_L_64:
$040D	$	Khawad_L_65:
;Khawad.ppas,86 :: 		if (Strcmp(data,'ANAL2') = 0) then
$040D	$3027			MOVLW	_data
$040E	$00D6			MOVWF	FARG_strcmp
$040F	$3041			MOVLW	65
$0410	$00C1			MOVWF	?main_Local_Text+0
$0411	$304E			MOVLW	78
$0412	$00C2			MOVWF	?main_Local_Text+1
$0413	$3041			MOVLW	65
$0414	$00C3			MOVWF	?main_Local_Text+2
$0415	$304C			MOVLW	76
$0416	$00C4			MOVWF	?main_Local_Text+3
$0417	$3032			MOVLW	50
$0418	$00C5			MOVWF	?main_Local_Text+4
$0419	$01C6			CLRF	?main_Local_Text+5
$041A	$3041			MOVLW	?main_Local_Text
$041B	$00D7			MOVWF	FARG_strcmp+1
$041C	$158A			BSF	PCLATH, 3
$041D	$2043			CALL	_strcmp
$041E	$118A			BCF	PCLATH, 3
$041F	$3000			MOVLW	0
$0420	$0671			XORWF	STACK_0+1, 0
$0421	$1D03			BTFSS	STATUS, Z
$0422	$2C25			GOTO	L_main_18
$0423	$3000			MOVLW	0
$0424	$0670			XORWF	STACK_0, 0
$0425	$	L_main_18:
$0425	$1D03			BTFSS	STATUS, Z
$0426	$2C85			GOTO	Khawad_L_67
$0427	$	Khawad_L_66:
;Khawad.ppas,88 :: 		H:= adc_read(2);
$0427	$3002			MOVLW	2
$0428	$00D6			MOVWF	FARG_ADC_read
$0429	$158A			BSF	PCLATH, 3
$042A	$2089			CALL	_adc_read
$042B	$118A			BCF	PCLATH, 3
$042C	$0870			MOVF	STACK_0, 0
$042D	$00BD			MOVWF	_h
$042E	$0871			MOVF	STACK_0+1, 0
$042F	$00BE			MOVWF	_h+1
$0430	$01BF			CLRF	_h+2
$0431	$01C0			CLRF	_h+3
;Khawad.ppas,89 :: 		H:=(h*5000)/1024 ;
$0432	$083D			MOVF	_h, 0
$0433	$00F0			MOVWF	STACK_0
$0434	$083E			MOVF	_h+1, 0
$0435	$00F1			MOVWF	STACK_0+1
$0436	$083F			MOVF	_h+2, 0
$0437	$00F2			MOVWF	STACK_0+2
$0438	$0840			MOVF	_h+3, 0
$0439	$00F3			MOVWF	STACK_0+3
$043A	$3088			MOVLW	136
$043B	$00F4			MOVWF	STACK_4
$043C	$3013			MOVLW	19
$043D	$00F5			MOVWF	STACK_4+1
$043E	$01F6			CLRF	STACK_4+2
$043F	$01F7			CLRF	STACK_4+3
$0440	$158A			BSF	PCLATH, 3
$0441	$20CA			CALL	_mul_32x32_s
$0442	$118A			BCF	PCLATH, 3
$0443	$3000			MOVLW	0
$0444	$00F4			MOVWF	STACK_4
$0445	$3004			MOVLW	4
$0446	$00F5			MOVWF	STACK_4+1
$0447	$01F6			CLRF	STACK_4+2
$0448	$01F7			CLRF	STACK_4+3
$0449	$264A			CALL	_div_32x32_s
$044A	$0870			MOVF	STACK_0, 0
$044B	$00BD			MOVWF	_h
$044C	$0871			MOVF	STACK_0+1, 0
$044D	$00BE			MOVWF	_h+1
$044E	$0872			MOVF	STACK_0+2, 0
$044F	$00BF			MOVWF	_h+2
$0450	$0873			MOVF	STACK_0+3, 0
$0451	$00C0			MOVWF	_h+3
;Khawad.ppas,90 :: 		wordtostr(h,data) ;
$0452	$0870			MOVF	STACK_0, 0
$0453	$00D6			MOVWF	FARG_WordToStr
$0454	$0871			MOVF	STACK_0+1, 0
$0455	$00D7			MOVWF	FARG_WordToStr+1
$0456	$3027			MOVLW	_data
$0457	$00D8			MOVWF	FARG_WordToStr+2
$0458	$26E6			CALL	_wordtostr
;Khawad.ppas,91 :: 		usart_write_text('ANAL 2 = ');
$0459	$3041			MOVLW	65
$045A	$00C1			MOVWF	?main_Local_Text+0
$045B	$304E			MOVLW	78
$045C	$00C2			MOVWF	?main_Local_Text+1
$045D	$3041			MOVLW	65
$045E	$00C3			MOVWF	?main_Local_Text+2
$045F	$304C			MOVLW	76
$0460	$00C4			MOVWF	?main_Local_Text+3
$0461	$3020			MOVLW	32
$0462	$00C5			MOVWF	?main_Local_Text+4
$0463	$3032			MOVLW	50
$0464	$00C6			MOVWF	?main_Local_Text+5
$0465	$3020			MOVLW	32
$0466	$00C7			MOVWF	?main_Local_Text+6
$0467	$303D			MOVLW	61
$0468	$00C8			MOVWF	?main_Local_Text+7
$0469	$3020			MOVLW	32
$046A	$00C9			MOVWF	?main_Local_Text+8
$046B	$01CA			CLRF	?main_Local_Text+9
$046C	$3041			MOVLW	?main_Local_Text
$046D	$00D6			MOVWF	FARG_Usart_Write_Text
$046E	$158A			BSF	PCLATH, 3
$046F	$2159			CALL	_usart_write_text
$0470	$118A			BCF	PCLATH, 3
;Khawad.ppas,92 :: 		usart_write_text(data);
$0471	$3027			MOVLW	_data
$0472	$00D6			MOVWF	FARG_Usart_Write_Text
$0473	$158A			BSF	PCLATH, 3
$0474	$2159			CALL	_usart_write_text
$0475	$118A			BCF	PCLATH, 3
;Khawad.ppas,93 :: 		usart_write_text('mV');
$0476	$306D			MOVLW	109
$0477	$00C1			MOVWF	?main_Local_Text+0
$0478	$3056			MOVLW	86
$0479	$00C2			MOVWF	?main_Local_Text+1
$047A	$01C3			CLRF	?main_Local_Text+2
$047B	$3041			MOVLW	?main_Local_Text
$047C	$00D6			MOVWF	FARG_Usart_Write_Text
$047D	$158A			BSF	PCLATH, 3
$047E	$2159			CALL	_usart_write_text
$047F	$118A			BCF	PCLATH, 3
;Khawad.ppas,94 :: 		usart_write(13);
$0480	$300D			MOVLW	13
$0481	$00DD			MOVWF	FARG_USART_Write
$0482	$158A			BSF	PCLATH, 3
$0483	$2182			CALL	_usart_write
$0484	$118A			BCF	PCLATH, 3
;Khawad.ppas,95 :: 		end;
$0485	$	Khawad_L_67:
$0485	$	Khawad_L_68:
;Khawad.ppas,96 :: 		if (Strcmp(data,'ANAL3') = 0) then
$0485	$3027			MOVLW	_data
$0486	$00D6			MOVWF	FARG_strcmp
$0487	$3041			MOVLW	65
$0488	$00C1			MOVWF	?main_Local_Text+0
$0489	$304E			MOVLW	78
$048A	$00C2			MOVWF	?main_Local_Text+1
$048B	$3041			MOVLW	65
$048C	$00C3			MOVWF	?main_Local_Text+2
$048D	$304C			MOVLW	76
$048E	$00C4			MOVWF	?main_Local_Text+3
$048F	$3033			MOVLW	51
$0490	$00C5			MOVWF	?main_Local_Text+4
$0491	$01C6			CLRF	?main_Local_Text+5
$0492	$3041			MOVLW	?main_Local_Text
$0493	$00D7			MOVWF	FARG_strcmp+1
$0494	$158A			BSF	PCLATH, 3
$0495	$2043			CALL	_strcmp
$0496	$118A			BCF	PCLATH, 3
$0497	$3000			MOVLW	0
$0498	$0671			XORWF	STACK_0+1, 0
$0499	$1D03			BTFSS	STATUS, Z
$049A	$2C9D			GOTO	L_main_19
$049B	$3000			MOVLW	0
$049C	$0670			XORWF	STACK_0, 0
$049D	$	L_main_19:
$049D	$1D03			BTFSS	STATUS, Z
$049E	$2CFD			GOTO	Khawad_L_70
$049F	$	Khawad_L_69:
;Khawad.ppas,98 :: 		H:= adc_read(3);
$049F	$3003			MOVLW	3
$04A0	$00D6			MOVWF	FARG_ADC_read
$04A1	$158A			BSF	PCLATH, 3
$04A2	$2089			CALL	_adc_read
$04A3	$118A			BCF	PCLATH, 3
$04A4	$0870			MOVF	STACK_0, 0
$04A5	$00BD			MOVWF	_h
$04A6	$0871			MOVF	STACK_0+1, 0
$04A7	$00BE			MOVWF	_h+1
$04A8	$01BF			CLRF	_h+2
$04A9	$01C0			CLRF	_h+3
;Khawad.ppas,99 :: 		H:=(h*5000)/1024 ;
$04AA	$083D			MOVF	_h, 0
$04AB	$00F0			MOVWF	STACK_0
$04AC	$083E			MOVF	_h+1, 0
$04AD	$00F1			MOVWF	STACK_0+1
$04AE	$083F			MOVF	_h+2, 0
$04AF	$00F2			MOVWF	STACK_0+2
$04B0	$0840			MOVF	_h+3, 0
$04B1	$00F3			MOVWF	STACK_0+3
$04B2	$3088			MOVLW	136
$04B3	$00F4			MOVWF	STACK_4
$04B4	$3013			MOVLW	19
$04B5	$00F5			MOVWF	STACK_4+1
$04B6	$01F6			CLRF	STACK_4+2
$04B7	$01F7			CLRF	STACK_4+3
$04B8	$158A			BSF	PCLATH, 3
$04B9	$20CA			CALL	_mul_32x32_s
$04BA	$118A			BCF	PCLATH, 3
$04BB	$3000			MOVLW	0
$04BC	$00F4			MOVWF	STACK_4
$04BD	$3004			MOVLW	4
$04BE	$00F5			MOVWF	STACK_4+1
$04BF	$01F6			CLRF	STACK_4+2
$04C0	$01F7			CLRF	STACK_4+3
$04C1	$264A			CALL	_div_32x32_s
$04C2	$0870			MOVF	STACK_0, 0
$04C3	$00BD			MOVWF	_h
$04C4	$0871			MOVF	STACK_0+1, 0
$04C5	$00BE			MOVWF	_h+1
$04C6	$0872			MOVF	STACK_0+2, 0
$04C7	$00BF			MOVWF	_h+2
$04C8	$0873			MOVF	STACK_0+3, 0
$04C9	$00C0			MOVWF	_h+3
;Khawad.ppas,100 :: 		wordtostr(h,data) ;
$04CA	$0870			MOVF	STACK_0, 0
$04CB	$00D6			MOVWF	FARG_WordToStr
$04CC	$0871			MOVF	STACK_0+1, 0
$04CD	$00D7			MOVWF	FARG_WordToStr+1
$04CE	$3027			MOVLW	_data
$04CF	$00D8			MOVWF	FARG_WordToStr+2
$04D0	$26E6			CALL	_wordtostr
;Khawad.ppas,101 :: 		usart_write_text('ANAL 3 = ');
$04D1	$3041			MOVLW	65
$04D2	$00C1			MOVWF	?main_Local_Text+0
$04D3	$304E			MOVLW	78
$04D4	$00C2			MOVWF	?main_Local_Text+1
$04D5	$3041			MOVLW	65
$04D6	$00C3			MOVWF	?main_Local_Text+2
$04D7	$304C			MOVLW	76
$04D8	$00C4			MOVWF	?main_Local_Text+3
$04D9	$3020			MOVLW	32
$04DA	$00C5			MOVWF	?main_Local_Text+4
$04DB	$3033			MOVLW	51
$04DC	$00C6			MOVWF	?main_Local_Text+5
$04DD	$3020			MOVLW	32
$04DE	$00C7			MOVWF	?main_Local_Text+6
$04DF	$303D			MOVLW	61
$04E0	$00C8			MOVWF	?main_Local_Text+7
$04E1	$3020			MOVLW	32
$04E2	$00C9			MOVWF	?main_Local_Text+8
$04E3	$01CA			CLRF	?main_Local_Text+9
$04E4	$3041			MOVLW	?main_Local_Text
$04E5	$00D6			MOVWF	FARG_Usart_Write_Text
$04E6	$158A			BSF	PCLATH, 3
$04E7	$2159			CALL	_usart_write_text
$04E8	$118A			BCF	PCLATH, 3
;Khawad.ppas,102 :: 		usart_write_text(data);
$04E9	$3027			MOVLW	_data
$04EA	$00D6			MOVWF	FARG_Usart_Write_Text
$04EB	$158A			BSF	PCLATH, 3
$04EC	$2159			CALL	_usart_write_text
$04ED	$118A			BCF	PCLATH, 3
;Khawad.ppas,103 :: 		usart_write_text('mV');
$04EE	$306D			MOVLW	109
$04EF	$00C1			MOVWF	?main_Local_Text+0
$04F0	$3056			MOVLW	86
$04F1	$00C2			MOVWF	?main_Local_Text+1
$04F2	$01C3			CLRF	?main_Local_Text+2
$04F3	$3041			MOVLW	?main_Local_Text
$04F4	$00D6			MOVWF	FARG_Usart_Write_Text
$04F5	$158A			BSF	PCLATH, 3
$04F6	$2159			CALL	_usart_write_text
$04F7	$118A			BCF	PCLATH, 3
;Khawad.ppas,104 :: 		usart_write(13);
$04F8	$300D			MOVLW	13
$04F9	$00DD			MOVWF	FARG_USART_Write
$04FA	$158A			BSF	PCLATH, 3
$04FB	$2182			CALL	_usart_write
$04FC	$118A			BCF	PCLATH, 3
;Khawad.ppas,105 :: 		end;
$04FD	$	Khawad_L_70:
$04FD	$	Khawad_L_71:
;Khawad.ppas,107 :: 		delay_ms(1);
$04FD	$3007			MOVLW	7
$04FE	$00FB			MOVWF	STACK_11
$04FF	$30FF			MOVLW	255
$0500	$00FA			MOVWF	STACK_10
$0501	$0BFB			DECFSZ	STACK_11, F
$0502	$2D04			GOTO	$+2
$0503	$2D07			GOTO	$+4
$0504	$0BFA			DECFSZ	STACK_10, F
$0505	$2D04			GOTO	$-1
$0506	$2D01			GOTO	$-5
$0507	$3078			MOVLW	120
$0508	$00FA			MOVWF	STACK_10
$0509	$0BFA			DECFSZ	STACK_10, F
$050A	$2D09			GOTO	$-1
$050B	$0000			NOP
$050C	$0000			NOP
;Khawad.ppas,108 :: 		data[0]:=0;
$050D	$01A7			CLRF	_data+0, 1
;Khawad.ppas,109 :: 		end;
$050E	$0826			MOVF	_i+1, 0
$050F	$3A03			XORLW	3
$0510	$1D03			BTFSS	STATUS, Z
$0511	$2D14			GOTO	L_main_20
$0512	$30E8			MOVLW	232
$0513	$0625			XORWF	_i, 0
$0514	$	L_main_20:
$0514	$1903			BTFSC	STATUS, Z
$0515	$2D1A			GOTO	Khawad_L_9
$0516	$	Khawad_L_7:
$0516	$0AA5			INCF	_i, 1
$0517	$1903			BTFSC	STATUS, Z
$0518	$0AA6			INCF	_i+1, 1
$0519	$29BB			GOTO	Khawad_L_6
$051A	$	Khawad_L_9:
;Khawad.ppas,110 :: 		end;
$051A	$299C			GOTO	Khawad_L_2
;Khawad.ppas,111 :: 		end.
$051B	$2D1B			GOTO	$
